# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PacketSender(object):
    def setupUi(self, PacketSender):
        PacketSender.setObjectName("PacketSender")
        PacketSender.resize(1440, 855)
        PacketSender.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(PacketSender)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboInterfacesBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboInterfacesBox.setAccessibleDescription("")
        self.comboInterfacesBox.setObjectName("comboInterfacesBox")
        self.gridLayout_2.addWidget(self.comboInterfacesBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(232, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.pushButton_Bottom_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bottom_Save.setObjectName("pushButton_Bottom_Save")
        self.verticalLayout_29.addWidget(self.pushButton_Bottom_Save)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_29.addWidget(self.pushButton_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_29)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.listWidget_Bottom_Packets = QListWidgetSavedPackets(self.centralwidget)
        self.listWidget_Bottom_Packets.setObjectName("listWidget_Bottom_Packets")
        self.verticalLayout_17.addWidget(self.listWidget_Bottom_Packets)
        self.pushButton_Bottom_Packets_Refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bottom_Packets_Refresh.setObjectName("pushButton_Bottom_Packets_Refresh")
        self.verticalLayout_17.addWidget(self.pushButton_Bottom_Packets_Refresh)
        self.horizontalLayout_5.addLayout(self.verticalLayout_17)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.pushButton_Bottom_ToQueue = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bottom_ToQueue.setObjectName("pushButton_Bottom_ToQueue")
        self.verticalLayout_26.addWidget(self.pushButton_Bottom_ToQueue)
        self.pushButton_Bottom_Queue_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bottom_Queue_Delete.setObjectName("pushButton_Bottom_Queue_Delete")
        self.verticalLayout_26.addWidget(self.pushButton_Bottom_Queue_Delete)
        self.horizontalLayout_5.addLayout(self.verticalLayout_26)
        self.listWidget_Bottom_Queue = QListWidgetPacketsQueue(self.centralwidget)
        self.listWidget_Bottom_Queue.setObjectName("listWidget_Bottom_Queue")
        self.horizontalLayout_5.addWidget(self.listWidget_Bottom_Queue)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 0, 5, 1, 1)
        self.delaySpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.delaySpinBox.setEnabled(True)
        self.delaySpinBox.setMaximum(10000)
        self.delaySpinBox.setSingleStep(10)
        self.delaySpinBox.setProperty("value", 10)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.gridLayout.addWidget(self.delaySpinBox, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.timesSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.timesSpinBox.setMaximum(10000)
        self.timesSpinBox.setProperty("value", 1)
        self.timesSpinBox.setObjectName("timesSpinBox")
        self.gridLayout.addWidget(self.timesSpinBox, 0, 1, 1, 1)
        self.label_icmp_DF = QtWidgets.QLabel(self.centralwidget)
        self.label_icmp_DF.setObjectName("label_icmp_DF")
        self.gridLayout.addWidget(self.label_icmp_DF, 0, 2, 1, 1)
        self.pushButton_Bottom_RefreshAll = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Bottom_RefreshAll.setObjectName("pushButton_Bottom_RefreshAll")
        self.gridLayout.addWidget(self.pushButton_Bottom_RefreshAll, 0, 6, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_12.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tab_L4_Widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_L4_Widget.setUsesScrollButtons(False)
        self.tab_L4_Widget.setObjectName("tab_L4_Widget")
        self.tcp = QtWidgets.QWidget()
        self.tcp.setObjectName("tcp")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tcp)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_tcp_SRCPort = QtWidgets.QLabel(self.tcp)
        self.label_tcp_SRCPort.setObjectName("label_tcp_SRCPort")
        self.horizontalLayout_9.addWidget(self.label_tcp_SRCPort)
        self.spinBox_tcp_SRCPort = QtWidgets.QSpinBox(self.tcp)
        self.spinBox_tcp_SRCPort.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_tcp_SRCPort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_tcp_SRCPort.setWhatsThis("")
        self.spinBox_tcp_SRCPort.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_tcp_SRCPort.setSuffix("")
        self.spinBox_tcp_SRCPort.setMaximum(65535)
        self.spinBox_tcp_SRCPort.setDisplayIntegerBase(10)
        self.spinBox_tcp_SRCPort.setObjectName("spinBox_tcp_SRCPort")
        self.horizontalLayout_9.addWidget(self.spinBox_tcp_SRCPort)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_tcp_DSTPort = QtWidgets.QLabel(self.tcp)
        self.label_tcp_DSTPort.setObjectName("label_tcp_DSTPort")
        self.horizontalLayout_8.addWidget(self.label_tcp_DSTPort)
        self.spinBox_tcp_DSTPort = QtWidgets.QSpinBox(self.tcp)
        self.spinBox_tcp_DSTPort.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_tcp_DSTPort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_tcp_DSTPort.setWhatsThis("")
        self.spinBox_tcp_DSTPort.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_tcp_DSTPort.setSuffix("")
        self.spinBox_tcp_DSTPort.setMaximum(65535)
        self.spinBox_tcp_DSTPort.setProperty("value", 8000)
        self.spinBox_tcp_DSTPort.setDisplayIntegerBase(10)
        self.spinBox_tcp_DSTPort.setObjectName("spinBox_tcp_DSTPort")
        self.horizontalLayout_8.addWidget(self.spinBox_tcp_DSTPort)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_tcp_SEQNum = QtWidgets.QLabel(self.tcp)
        self.label_tcp_SEQNum.setObjectName("label_tcp_SEQNum")
        self.horizontalLayout_10.addWidget(self.label_tcp_SEQNum)
        self.spinBox_tcp_SEQ = QtWidgets.QSpinBox(self.tcp)
        self.spinBox_tcp_SEQ.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_tcp_SEQ.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_tcp_SEQ.setWhatsThis("")
        self.spinBox_tcp_SEQ.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_tcp_SEQ.setSuffix("")
        self.spinBox_tcp_SEQ.setMinimum(-2147483647)
        self.spinBox_tcp_SEQ.setMaximum(2147483646)
        self.spinBox_tcp_SEQ.setDisplayIntegerBase(10)
        self.spinBox_tcp_SEQ.setObjectName("spinBox_tcp_SEQ")
        self.horizontalLayout_10.addWidget(self.spinBox_tcp_SEQ)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_tcp_ACKNum = QtWidgets.QLabel(self.tcp)
        self.label_tcp_ACKNum.setObjectName("label_tcp_ACKNum")
        self.horizontalLayout_11.addWidget(self.label_tcp_ACKNum)
        self.spinBox_tcp_ACK = QtWidgets.QSpinBox(self.tcp)
        self.spinBox_tcp_ACK.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_tcp_ACK.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_tcp_ACK.setWhatsThis("")
        self.spinBox_tcp_ACK.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_tcp_ACK.setSuffix("")
        self.spinBox_tcp_ACK.setMinimum(-2147483647)
        self.spinBox_tcp_ACK.setMaximum(2147483646)
        self.spinBox_tcp_ACK.setDisplayIntegerBase(10)
        self.spinBox_tcp_ACK.setObjectName("spinBox_tcp_ACK")
        self.horizontalLayout_11.addWidget(self.spinBox_tcp_ACK)
        self.gridLayout_8.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_tcp_DataOffset = QtWidgets.QLabel(self.tcp)
        self.label_tcp_DataOffset.setObjectName("label_tcp_DataOffset")
        self.horizontalLayout_12.addWidget(self.label_tcp_DataOffset)
        self.spinBox_tcp_DataOffset = QtWidgets.QSpinBox(self.tcp)
        self.spinBox_tcp_DataOffset.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_tcp_DataOffset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_tcp_DataOffset.setWhatsThis("")
        self.spinBox_tcp_DataOffset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_tcp_DataOffset.setSuffix("")
        self.spinBox_tcp_DataOffset.setMinimum(0)
        self.spinBox_tcp_DataOffset.setMaximum(15)
        self.spinBox_tcp_DataOffset.setDisplayIntegerBase(10)
        self.spinBox_tcp_DataOffset.setObjectName("spinBox_tcp_DataOffset")
        self.horizontalLayout_12.addWidget(self.spinBox_tcp_DataOffset)
        self.gridLayout_8.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_tcp_ReservetBits = QtWidgets.QLabel(self.tcp)
        self.label_tcp_ReservetBits.setObjectName("label_tcp_ReservetBits")
        self.horizontalLayout_13.addWidget(self.label_tcp_ReservetBits)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_tcp_Res1 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_Res1.setObjectName("checkBox_tcp_Res1")
        self.horizontalLayout_2.addWidget(self.checkBox_tcp_Res1)
        self.checkBox_tcp_Res2 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_Res2.setObjectName("checkBox_tcp_Res2")
        self.horizontalLayout_2.addWidget(self.checkBox_tcp_Res2)
        self.checkBox_tcp_Res3 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_Res3.setObjectName("checkBox_tcp_Res3")
        self.horizontalLayout_2.addWidget(self.checkBox_tcp_Res3)
        self.checkBox_tcp_Res4 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_Res4.setObjectName("checkBox_tcp_Res4")
        self.horizontalLayout_2.addWidget(self.checkBox_tcp_Res4)
        self.checkBox_tcp_CWR = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_CWR.setObjectName("checkBox_tcp_CWR")
        self.horizontalLayout_2.addWidget(self.checkBox_tcp_CWR)
        self.checkBox_tcp_ECE = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_ECE.setObjectName("checkBox_tcp_ECE")
        self.horizontalLayout_2.addWidget(self.checkBox_tcp_ECE)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_tcp_ControlBits = QtWidgets.QLabel(self.tcp)
        self.label_tcp_ControlBits.setObjectName("label_tcp_ControlBits")
        self.horizontalLayout_14.addWidget(self.label_tcp_ControlBits)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_tcp_URG = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_URG.setObjectName("checkBox_tcp_URG")
        self.horizontalLayout_4.addWidget(self.checkBox_tcp_URG)
        self.checkBox_tcp_ACK = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_ACK.setObjectName("checkBox_tcp_ACK")
        self.horizontalLayout_4.addWidget(self.checkBox_tcp_ACK)
        self.checkBox_tcp_PSH = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_PSH.setObjectName("checkBox_tcp_PSH")
        self.horizontalLayout_4.addWidget(self.checkBox_tcp_PSH)
        self.checkBox_tcp_RST = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_RST.setObjectName("checkBox_tcp_RST")
        self.horizontalLayout_4.addWidget(self.checkBox_tcp_RST)
        self.checkBox_tcp_SYN = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_SYN.setObjectName("checkBox_tcp_SYN")
        self.horizontalLayout_4.addWidget(self.checkBox_tcp_SYN)
        self.checkBox_tcp_FIN = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_FIN.setObjectName("checkBox_tcp_FIN")
        self.horizontalLayout_4.addWidget(self.checkBox_tcp_FIN)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_4)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_tcp_WIN = QtWidgets.QLabel(self.tcp)
        self.label_tcp_WIN.setObjectName("label_tcp_WIN")
        self.horizontalLayout_15.addWidget(self.label_tcp_WIN)
        self.spinBox_tcp_WIN = QtWidgets.QSpinBox(self.tcp)
        self.spinBox_tcp_WIN.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_tcp_WIN.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_tcp_WIN.setWhatsThis("")
        self.spinBox_tcp_WIN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_tcp_WIN.setSuffix("")
        self.spinBox_tcp_WIN.setMinimum(0)
        self.spinBox_tcp_WIN.setMaximum(2147483646)
        self.spinBox_tcp_WIN.setDisplayIntegerBase(10)
        self.spinBox_tcp_WIN.setObjectName("spinBox_tcp_WIN")
        self.horizontalLayout_15.addWidget(self.spinBox_tcp_WIN)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 7, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_tcp_Checksum = QtWidgets.QLabel(self.tcp)
        self.label_tcp_Checksum.setObjectName("label_tcp_Checksum")
        self.horizontalLayout_16.addWidget(self.label_tcp_Checksum)
        self.lineEdit_tcp_Checksum = QtWidgets.QLineEdit(self.tcp)
        self.lineEdit_tcp_Checksum.setObjectName("lineEdit_tcp_Checksum")
        self.horizontalLayout_16.addWidget(self.lineEdit_tcp_Checksum)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 8, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_tcp_UrgentPointers = QtWidgets.QLabel(self.tcp)
        self.label_tcp_UrgentPointers.setObjectName("label_tcp_UrgentPointers")
        self.horizontalLayout_17.addWidget(self.label_tcp_UrgentPointers)
        self.spinBox_tcp_Urgent = QtWidgets.QSpinBox(self.tcp)
        self.spinBox_tcp_Urgent.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_tcp_Urgent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_tcp_Urgent.setWhatsThis("")
        self.spinBox_tcp_Urgent.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_tcp_Urgent.setSuffix("")
        self.spinBox_tcp_Urgent.setMinimum(0)
        self.spinBox_tcp_Urgent.setMaximum(2147483646)
        self.spinBox_tcp_Urgent.setDisplayIntegerBase(10)
        self.spinBox_tcp_Urgent.setObjectName("spinBox_tcp_Urgent")
        self.horizontalLayout_17.addWidget(self.spinBox_tcp_Urgent)
        self.gridLayout_8.addLayout(self.horizontalLayout_17, 9, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_tcp_Options = QtWidgets.QLabel(self.tcp)
        self.label_tcp_Options.setObjectName("label_tcp_Options")
        self.horizontalLayout_18.addWidget(self.label_tcp_Options)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_tcp_Nops = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_Nops.setObjectName("checkBox_tcp_Nops")
        self.verticalLayout_2.addWidget(self.checkBox_tcp_Nops)
        self.checkBox_tcp_Timestamp = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_tcp_Timestamp.setObjectName("checkBox_tcp_Timestamp")
        self.verticalLayout_2.addWidget(self.checkBox_tcp_Timestamp)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 10, 0, 1, 1)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_tcp_Data = QtWidgets.QLabel(self.tcp)
        self.label_tcp_Data.setEnabled(True)
        self.label_tcp_Data.setObjectName("label_tcp_Data")
        self.horizontalLayout_43.addWidget(self.label_tcp_Data)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.plainTextEdit_tcp_Data = QtWidgets.QPlainTextEdit(self.tcp)
        self.plainTextEdit_tcp_Data.setEnabled(True)
        self.plainTextEdit_tcp_Data.setPlaceholderText("")
        self.plainTextEdit_tcp_Data.setObjectName("plainTextEdit_tcp_Data")
        self.verticalLayout_12.addWidget(self.plainTextEdit_tcp_Data)
        self.pushButton_6 = QtWidgets.QPushButton(self.tcp)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_12.addWidget(self.pushButton_6)
        self.horizontalLayout_43.addLayout(self.verticalLayout_12)
        self.gridLayout_8.addLayout(self.horizontalLayout_43, 11, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tab_L4_Widget.addTab(self.tcp, "")
        self.udp = QtWidgets.QWidget()
        self.udp.setObjectName("udp")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.udp)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_udp_SRCPort = QtWidgets.QLabel(self.udp)
        self.label_udp_SRCPort.setObjectName("label_udp_SRCPort")
        self.horizontalLayout_39.addWidget(self.label_udp_SRCPort)
        self.spinBox_udp_SRCPort = QtWidgets.QSpinBox(self.udp)
        self.spinBox_udp_SRCPort.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_udp_SRCPort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_udp_SRCPort.setWhatsThis("")
        self.spinBox_udp_SRCPort.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_udp_SRCPort.setSuffix("")
        self.spinBox_udp_SRCPort.setMaximum(65535)
        self.spinBox_udp_SRCPort.setDisplayIntegerBase(10)
        self.spinBox_udp_SRCPort.setObjectName("spinBox_udp_SRCPort")
        self.horizontalLayout_39.addWidget(self.spinBox_udp_SRCPort)
        self.verticalLayout_6.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_udp_DSTPort = QtWidgets.QLabel(self.udp)
        self.label_udp_DSTPort.setObjectName("label_udp_DSTPort")
        self.horizontalLayout_38.addWidget(self.label_udp_DSTPort)
        self.spinBox_udp_DSTPort = QtWidgets.QSpinBox(self.udp)
        self.spinBox_udp_DSTPort.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_udp_DSTPort.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_udp_DSTPort.setWhatsThis("")
        self.spinBox_udp_DSTPort.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_udp_DSTPort.setSuffix("")
        self.spinBox_udp_DSTPort.setMaximum(65535)
        self.spinBox_udp_DSTPort.setProperty("value", 8000)
        self.spinBox_udp_DSTPort.setDisplayIntegerBase(10)
        self.spinBox_udp_DSTPort.setObjectName("spinBox_udp_DSTPort")
        self.horizontalLayout_38.addWidget(self.spinBox_udp_DSTPort)
        self.verticalLayout_6.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_udp_length = QtWidgets.QLabel(self.udp)
        self.label_udp_length.setObjectName("label_udp_length")
        self.horizontalLayout_40.addWidget(self.label_udp_length)
        self.spinBox_udp_Length = QtWidgets.QSpinBox(self.udp)
        self.spinBox_udp_Length.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_udp_Length.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_udp_Length.setWhatsThis("")
        self.spinBox_udp_Length.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_udp_Length.setSuffix("")
        self.spinBox_udp_Length.setMaximum(65535)
        self.spinBox_udp_Length.setDisplayIntegerBase(10)
        self.spinBox_udp_Length.setObjectName("spinBox_udp_Length")
        self.horizontalLayout_40.addWidget(self.spinBox_udp_Length)
        self.verticalLayout_6.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_udp_checksum = QtWidgets.QLabel(self.udp)
        self.label_udp_checksum.setObjectName("label_udp_checksum")
        self.horizontalLayout_41.addWidget(self.label_udp_checksum)
        self.lineEdit_udp_Checksum = QtWidgets.QLineEdit(self.udp)
        self.lineEdit_udp_Checksum.setObjectName("lineEdit_udp_Checksum")
        self.horizontalLayout_41.addWidget(self.lineEdit_udp_Checksum)
        self.verticalLayout_6.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_udp_Data = QtWidgets.QLabel(self.udp)
        self.label_udp_Data.setEnabled(True)
        self.label_udp_Data.setObjectName("label_udp_Data")
        self.horizontalLayout_44.addWidget(self.label_udp_Data)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.plainTextEdit_udp_Data = QtWidgets.QPlainTextEdit(self.udp)
        self.plainTextEdit_udp_Data.setEnabled(True)
        self.plainTextEdit_udp_Data.setPlaceholderText("")
        self.plainTextEdit_udp_Data.setObjectName("plainTextEdit_udp_Data")
        self.verticalLayout_14.addWidget(self.plainTextEdit_udp_Data)
        self.pushButton_7 = QtWidgets.QPushButton(self.udp)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_14.addWidget(self.pushButton_7)
        self.horizontalLayout_44.addLayout(self.verticalLayout_14)
        self.verticalLayout_6.addLayout(self.horizontalLayout_44)
        self.gridLayout_7.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tab_L4_Widget.addTab(self.udp, "")
        self.horizontalLayout_3.addWidget(self.tab_L4_Widget)
        self.tab_L3_Widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_L3_Widget.setObjectName("tab_L3_Widget")
        self.ipv4 = QtWidgets.QWidget()
        self.ipv4.setObjectName("ipv4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ipv4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_ipv4_TTL = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_TTL.setObjectName("label_ipv4_TTL")
        self.horizontalLayout_27.addWidget(self.label_ipv4_TTL)
        self.spinBox_ipv4_TTL = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_TTL.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_TTL.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_TTL.setWhatsThis("")
        self.spinBox_ipv4_TTL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_TTL.setSuffix("")
        self.spinBox_ipv4_TTL.setMaximum(255)
        self.spinBox_ipv4_TTL.setProperty("value", 64)
        self.spinBox_ipv4_TTL.setDisplayIntegerBase(10)
        self.spinBox_ipv4_TTL.setObjectName("spinBox_ipv4_TTL")
        self.horizontalLayout_27.addWidget(self.spinBox_ipv4_TTL)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_ipv4_Protocol = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_Protocol.setObjectName("label_ipv4_Protocol")
        self.horizontalLayout_28.addWidget(self.label_ipv4_Protocol)
        self.spinBox_ipv4_Protocol = PSIpProtoSpinBox(self.ipv4)
        self.spinBox_ipv4_Protocol.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_Protocol.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_Protocol.setWhatsThis("")
        self.spinBox_ipv4_Protocol.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_Protocol.setSuffix("")
        self.spinBox_ipv4_Protocol.setMaximum(255)
        self.spinBox_ipv4_Protocol.setProperty("value", 6)
        self.spinBox_ipv4_Protocol.setDisplayIntegerBase(10)
        self.spinBox_ipv4_Protocol.setObjectName("spinBox_ipv4_Protocol")
        self.horizontalLayout_28.addWidget(self.spinBox_ipv4_Protocol)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_ipv4_Checksum = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_Checksum.setObjectName("label_ipv4_Checksum")
        self.horizontalLayout_29.addWidget(self.label_ipv4_Checksum)
        self.lineEdit_ipv4_Checksum = QtWidgets.QLineEdit(self.ipv4)
        self.lineEdit_ipv4_Checksum.setObjectName("lineEdit_ipv4_Checksum")
        self.horizontalLayout_29.addWidget(self.lineEdit_ipv4_Checksum)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_ipv4_SRCIP = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_SRCIP.setObjectName("label_ipv4_SRCIP")
        self.horizontalLayout_30.addWidget(self.label_ipv4_SRCIP)
        self.lineEdit_ipv4_SRCIP = QtWidgets.QLineEdit(self.ipv4)
        self.lineEdit_ipv4_SRCIP.setObjectName("lineEdit_ipv4_SRCIP")
        self.horizontalLayout_30.addWidget(self.lineEdit_ipv4_SRCIP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_ipv4_DSTIP = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_DSTIP.setObjectName("label_ipv4_DSTIP")
        self.horizontalLayout_31.addWidget(self.label_ipv4_DSTIP)
        self.lineEdit_ipv4_DSTIP = QtWidgets.QLineEdit(self.ipv4)
        self.lineEdit_ipv4_DSTIP.setClearButtonEnabled(False)
        self.lineEdit_ipv4_DSTIP.setObjectName("lineEdit_ipv4_DSTIP")
        self.horizontalLayout_31.addWidget(self.lineEdit_ipv4_DSTIP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_ipv4_Option = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_Option.setEnabled(False)
        self.label_ipv4_Option.setObjectName("label_ipv4_Option")
        self.horizontalLayout_36.addWidget(self.label_ipv4_Option)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_ipv4_options_Copied = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_ipv4_options_Copied.setEnabled(False)
        self.checkBox_ipv4_options_Copied.setObjectName("checkBox_ipv4_options_Copied")
        self.verticalLayout_7.addWidget(self.checkBox_ipv4_options_Copied)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_ipv4_options_Class = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_options_Class.setEnabled(False)
        self.label_ipv4_options_Class.setObjectName("label_ipv4_options_Class")
        self.horizontalLayout_32.addWidget(self.label_ipv4_options_Class)
        self.spinBox_ipv4_options_Class = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_options_Class.setEnabled(False)
        self.spinBox_ipv4_options_Class.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_options_Class.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_options_Class.setWhatsThis("")
        self.spinBox_ipv4_options_Class.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_options_Class.setSuffix("")
        self.spinBox_ipv4_options_Class.setMinimum(0)
        self.spinBox_ipv4_options_Class.setMaximum(3)
        self.spinBox_ipv4_options_Class.setProperty("value", 0)
        self.spinBox_ipv4_options_Class.setDisplayIntegerBase(10)
        self.spinBox_ipv4_options_Class.setObjectName("spinBox_ipv4_options_Class")
        self.horizontalLayout_32.addWidget(self.spinBox_ipv4_options_Class)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_ipv4_options_Number = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_options_Number.setEnabled(False)
        self.label_ipv4_options_Number.setObjectName("label_ipv4_options_Number")
        self.horizontalLayout_33.addWidget(self.label_ipv4_options_Number)
        self.spinBox_ipv4_options_Number = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_options_Number.setEnabled(False)
        self.spinBox_ipv4_options_Number.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_options_Number.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_options_Number.setWhatsThis("")
        self.spinBox_ipv4_options_Number.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_options_Number.setSuffix("")
        self.spinBox_ipv4_options_Number.setMinimum(0)
        self.spinBox_ipv4_options_Number.setMaximum(31)
        self.spinBox_ipv4_options_Number.setProperty("value", 0)
        self.spinBox_ipv4_options_Number.setDisplayIntegerBase(10)
        self.spinBox_ipv4_options_Number.setObjectName("spinBox_ipv4_options_Number")
        self.horizontalLayout_33.addWidget(self.spinBox_ipv4_options_Number)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_ipv4_options_Length = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_options_Length.setEnabled(False)
        self.label_ipv4_options_Length.setObjectName("label_ipv4_options_Length")
        self.horizontalLayout_34.addWidget(self.label_ipv4_options_Length)
        self.spinBox_ipv4_options_Length = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_options_Length.setEnabled(False)
        self.spinBox_ipv4_options_Length.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_options_Length.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_options_Length.setWhatsThis("")
        self.spinBox_ipv4_options_Length.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_options_Length.setSuffix("")
        self.spinBox_ipv4_options_Length.setMinimum(0)
        self.spinBox_ipv4_options_Length.setMaximum(255)
        self.spinBox_ipv4_options_Length.setProperty("value", 0)
        self.spinBox_ipv4_options_Length.setDisplayIntegerBase(10)
        self.spinBox_ipv4_options_Length.setObjectName("spinBox_ipv4_options_Length")
        self.horizontalLayout_34.addWidget(self.spinBox_ipv4_options_Length)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_ipv4_options_Data = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_options_Data.setEnabled(False)
        self.label_ipv4_options_Data.setObjectName("label_ipv4_options_Data")
        self.horizontalLayout_35.addWidget(self.label_ipv4_options_Data)
        self.plainTextEdit_ipv4_options_Data = QtWidgets.QPlainTextEdit(self.ipv4)
        self.plainTextEdit_ipv4_options_Data.setEnabled(False)
        self.plainTextEdit_ipv4_options_Data.setObjectName("plainTextEdit_ipv4_options_Data")
        self.horizontalLayout_35.addWidget(self.plainTextEdit_ipv4_options_Data)
        self.verticalLayout_7.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.label_ipv4_Data = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_Data.setEnabled(True)
        self.label_ipv4_Data.setObjectName("label_ipv4_Data")
        self.horizontalLayout_72.addWidget(self.label_ipv4_Data)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit_ipv4_Data = QtWidgets.QPlainTextEdit(self.ipv4)
        self.plainTextEdit_ipv4_Data.setEnabled(True)
        self.plainTextEdit_ipv4_Data.setPlaceholderText("")
        self.plainTextEdit_ipv4_Data.setObjectName("plainTextEdit_ipv4_Data")
        self.verticalLayout_4.addWidget(self.plainTextEdit_ipv4_Data)
        self.pushButton = QtWidgets.QPushButton(self.ipv4)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_72.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_72)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_ipv4_Version = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_Version.setObjectName("label_ipv4_Version")
        self.horizontalLayout_7.addWidget(self.label_ipv4_Version)
        self.spinBox_ipv4_Version = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_Version.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_Version.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_Version.setWhatsThis("")
        self.spinBox_ipv4_Version.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_Version.setSuffix("")
        self.spinBox_ipv4_Version.setMinimum(0)
        self.spinBox_ipv4_Version.setMaximum(15)
        self.spinBox_ipv4_Version.setProperty("value", 4)
        self.spinBox_ipv4_Version.setDisplayIntegerBase(10)
        self.spinBox_ipv4_Version.setObjectName("spinBox_ipv4_Version")
        self.horizontalLayout_7.addWidget(self.spinBox_ipv4_Version)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_ipv4_IHL = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_IHL.setObjectName("label_ipv4_IHL")
        self.horizontalLayout_19.addWidget(self.label_ipv4_IHL)
        self.spinBox_ipv4_IHL = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_IHL.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_IHL.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_IHL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_IHL.setSuffix("")
        self.spinBox_ipv4_IHL.setMinimum(0)
        self.spinBox_ipv4_IHL.setMaximum(15)
        self.spinBox_ipv4_IHL.setProperty("value", 0)
        self.spinBox_ipv4_IHL.setDisplayIntegerBase(10)
        self.spinBox_ipv4_IHL.setObjectName("spinBox_ipv4_IHL")
        self.horizontalLayout_19.addWidget(self.spinBox_ipv4_IHL)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_ipv4_DSCP = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_DSCP.setObjectName("label_ipv4_DSCP")
        self.horizontalLayout_20.addWidget(self.label_ipv4_DSCP)
        self.spinBox_ipv4_DSCP = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_DSCP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_DSCP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_DSCP.setWhatsThis("")
        self.spinBox_ipv4_DSCP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_DSCP.setSuffix("")
        self.spinBox_ipv4_DSCP.setMinimum(0)
        self.spinBox_ipv4_DSCP.setMaximum(63)
        self.spinBox_ipv4_DSCP.setDisplayIntegerBase(10)
        self.spinBox_ipv4_DSCP.setObjectName("spinBox_ipv4_DSCP")
        self.horizontalLayout_20.addWidget(self.spinBox_ipv4_DSCP)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_ipv4_ECN = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_ECN.setObjectName("label_ipv4_ECN")
        self.horizontalLayout_21.addWidget(self.label_ipv4_ECN)
        self.spinBox_ipv4_ECN = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_ECN.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_ECN.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_ECN.setWhatsThis("")
        self.spinBox_ipv4_ECN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_ECN.setSuffix("")
        self.spinBox_ipv4_ECN.setMinimum(0)
        self.spinBox_ipv4_ECN.setMaximum(3)
        self.spinBox_ipv4_ECN.setDisplayIntegerBase(10)
        self.spinBox_ipv4_ECN.setObjectName("spinBox_ipv4_ECN")
        self.horizontalLayout_21.addWidget(self.spinBox_ipv4_ECN)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_ipv4_TotalLength = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_TotalLength.setObjectName("label_ipv4_TotalLength")
        self.horizontalLayout_22.addWidget(self.label_ipv4_TotalLength)
        self.spinBox_ipv4_TotalLength = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_TotalLength.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_TotalLength.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_TotalLength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_TotalLength.setSuffix("")
        self.spinBox_ipv4_TotalLength.setMinimum(0)
        self.spinBox_ipv4_TotalLength.setMaximum(65535)
        self.spinBox_ipv4_TotalLength.setProperty("value", 0)
        self.spinBox_ipv4_TotalLength.setDisplayIntegerBase(10)
        self.spinBox_ipv4_TotalLength.setObjectName("spinBox_ipv4_TotalLength")
        self.horizontalLayout_22.addWidget(self.spinBox_ipv4_TotalLength)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_ipv4_Identification = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_Identification.setObjectName("label_ipv4_Identification")
        self.horizontalLayout_25.addWidget(self.label_ipv4_Identification)
        self.spinBox_ipv4_Identification = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_Identification.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_Identification.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_Identification.setWhatsThis("")
        self.spinBox_ipv4_Identification.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_Identification.setSuffix("")
        self.spinBox_ipv4_Identification.setMaximum(65535)
        self.spinBox_ipv4_Identification.setProperty("value", 0)
        self.spinBox_ipv4_Identification.setDisplayIntegerBase(10)
        self.spinBox_ipv4_Identification.setObjectName("spinBox_ipv4_Identification")
        self.horizontalLayout_25.addWidget(self.spinBox_ipv4_Identification)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_ipv4_Flags = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_Flags.setObjectName("label_ipv4_Flags")
        self.horizontalLayout_24.addWidget(self.label_ipv4_Flags)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_ipv4_Res = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_ipv4_Res.setObjectName("checkBox_ipv4_Res")
        self.horizontalLayout_23.addWidget(self.checkBox_ipv4_Res)
        self.checkBox_ipv4_DF = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_ipv4_DF.setObjectName("checkBox_ipv4_DF")
        self.horizontalLayout_23.addWidget(self.checkBox_ipv4_DF)
        self.checkBox_ipv4_MF = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_ipv4_MF.setObjectName("checkBox_ipv4_MF")
        self.horizontalLayout_23.addWidget(self.checkBox_ipv4_MF)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_ipv4_FragmentOffset = QtWidgets.QLabel(self.ipv4)
        self.label_ipv4_FragmentOffset.setObjectName("label_ipv4_FragmentOffset")
        self.horizontalLayout_26.addWidget(self.label_ipv4_FragmentOffset)
        self.spinBox_ipv4_FragmentOffset = QtWidgets.QSpinBox(self.ipv4)
        self.spinBox_ipv4_FragmentOffset.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_ipv4_FragmentOffset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_ipv4_FragmentOffset.setWhatsThis("")
        self.spinBox_ipv4_FragmentOffset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_ipv4_FragmentOffset.setSuffix("")
        self.spinBox_ipv4_FragmentOffset.setMaximum(8191)
        self.spinBox_ipv4_FragmentOffset.setProperty("value", 0)
        self.spinBox_ipv4_FragmentOffset.setDisplayIntegerBase(10)
        self.spinBox_ipv4_FragmentOffset.setObjectName("spinBox_ipv4_FragmentOffset")
        self.horizontalLayout_26.addWidget(self.spinBox_ipv4_FragmentOffset)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tab_L3_Widget.addTab(self.ipv4, "")
        self.icmp = QtWidgets.QWidget()
        self.icmp.setObjectName("icmp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.icmp)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_icmp_Type = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Type.setObjectName("label_icmp_Type")
        self.horizontalLayout_48.addWidget(self.label_icmp_Type)
        self.spinBox_icmp_Type = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_Type.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_Type.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_Type.setWhatsThis("")
        self.spinBox_icmp_Type.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_Type.setSuffix("")
        self.spinBox_icmp_Type.setMinimum(0)
        self.spinBox_icmp_Type.setMaximum(255)
        self.spinBox_icmp_Type.setProperty("value", 0)
        self.spinBox_icmp_Type.setDisplayIntegerBase(10)
        self.spinBox_icmp_Type.setObjectName("spinBox_icmp_Type")
        self.horizontalLayout_48.addWidget(self.spinBox_icmp_Type)
        self.gridLayout_9.addLayout(self.horizontalLayout_48, 0, 0, 1, 1)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.label_icmp_Code = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Code.setObjectName("label_icmp_Code")
        self.horizontalLayout_64.addWidget(self.label_icmp_Code)
        self.spinBox_icmp_Code = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_Code.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_Code.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_Code.setWhatsThis("")
        self.spinBox_icmp_Code.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_Code.setSuffix("")
        self.spinBox_icmp_Code.setMinimum(0)
        self.spinBox_icmp_Code.setMaximum(255)
        self.spinBox_icmp_Code.setProperty("value", 0)
        self.spinBox_icmp_Code.setDisplayIntegerBase(10)
        self.spinBox_icmp_Code.setObjectName("spinBox_icmp_Code")
        self.horizontalLayout_64.addWidget(self.spinBox_icmp_Code)
        self.gridLayout_9.addLayout(self.horizontalLayout_64, 1, 0, 1, 1)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.label_icmp_Checksum = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Checksum.setObjectName("label_icmp_Checksum")
        self.horizontalLayout_65.addWidget(self.label_icmp_Checksum)
        self.lineEdit_icmp_Checksum = QtWidgets.QLineEdit(self.icmp)
        self.lineEdit_icmp_Checksum.setObjectName("lineEdit_icmp_Checksum")
        self.horizontalLayout_65.addWidget(self.lineEdit_icmp_Checksum)
        self.gridLayout_9.addLayout(self.horizontalLayout_65, 2, 0, 1, 1)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_icmp_ID = QtWidgets.QLabel(self.icmp)
        self.label_icmp_ID.setObjectName("label_icmp_ID")
        self.horizontalLayout_71.addWidget(self.label_icmp_ID)
        self.spinBox_icmp_id = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_id.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_id.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_id.setWhatsThis("")
        self.spinBox_icmp_id.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_id.setSuffix("")
        self.spinBox_icmp_id.setMinimum(0)
        self.spinBox_icmp_id.setMaximum(65535)
        self.spinBox_icmp_id.setProperty("value", 0)
        self.spinBox_icmp_id.setDisplayIntegerBase(10)
        self.spinBox_icmp_id.setObjectName("spinBox_icmp_id")
        self.horizontalLayout_71.addWidget(self.spinBox_icmp_id)
        self.gridLayout_9.addLayout(self.horizontalLayout_71, 3, 0, 1, 1)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.label_icmp_seq_number = QtWidgets.QLabel(self.icmp)
        self.label_icmp_seq_number.setObjectName("label_icmp_seq_number")
        self.horizontalLayout_73.addWidget(self.label_icmp_seq_number)
        self.spinBox_icmp_seqNum = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_seqNum.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_seqNum.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_seqNum.setWhatsThis("")
        self.spinBox_icmp_seqNum.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_seqNum.setSuffix("")
        self.spinBox_icmp_seqNum.setMinimum(0)
        self.spinBox_icmp_seqNum.setMaximum(65535)
        self.spinBox_icmp_seqNum.setProperty("value", 0)
        self.spinBox_icmp_seqNum.setDisplayIntegerBase(10)
        self.spinBox_icmp_seqNum.setObjectName("spinBox_icmp_seqNum")
        self.horizontalLayout_73.addWidget(self.spinBox_icmp_seqNum)
        self.gridLayout_9.addLayout(self.horizontalLayout_73, 4, 0, 1, 1)
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.label_udp_Data_2 = QtWidgets.QLabel(self.icmp)
        self.label_udp_Data_2.setEnabled(True)
        self.label_udp_Data_2.setObjectName("label_udp_Data_2")
        self.horizontalLayout_74.addWidget(self.label_udp_Data_2)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.plainTextEdit_udp_Data_2 = QtWidgets.QPlainTextEdit(self.icmp)
        self.plainTextEdit_udp_Data_2.setEnabled(True)
        self.plainTextEdit_udp_Data_2.setPlaceholderText("")
        self.plainTextEdit_udp_Data_2.setObjectName("plainTextEdit_udp_Data_2")
        self.verticalLayout_15.addWidget(self.plainTextEdit_udp_Data_2)
        self.pushButton_8 = QtWidgets.QPushButton(self.icmp)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_15.addWidget(self.pushButton_8)
        self.horizontalLayout_74.addLayout(self.verticalLayout_15)
        self.gridLayout_9.addLayout(self.horizontalLayout_74, 5, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_icmp_Version = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Version.setObjectName("label_icmp_Version")
        self.horizontalLayout_45.addWidget(self.label_icmp_Version)
        self.spinBox_icmp_Version = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_Version.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_Version.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_Version.setWhatsThis("")
        self.spinBox_icmp_Version.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_Version.setSuffix("")
        self.spinBox_icmp_Version.setMinimum(0)
        self.spinBox_icmp_Version.setMaximum(15)
        self.spinBox_icmp_Version.setProperty("value", 4)
        self.spinBox_icmp_Version.setDisplayIntegerBase(10)
        self.spinBox_icmp_Version.setObjectName("spinBox_icmp_Version")
        self.horizontalLayout_45.addWidget(self.spinBox_icmp_Version)
        self.verticalLayout_9.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_icmp_HeaderLenght = QtWidgets.QLabel(self.icmp)
        self.label_icmp_HeaderLenght.setObjectName("label_icmp_HeaderLenght")
        self.horizontalLayout_46.addWidget(self.label_icmp_HeaderLenght)
        self.spinBox_icmp_HeaderLenght = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_HeaderLenght.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_HeaderLenght.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_HeaderLenght.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_HeaderLenght.setSuffix("")
        self.spinBox_icmp_HeaderLenght.setMinimum(0)
        self.spinBox_icmp_HeaderLenght.setMaximum(15)
        self.spinBox_icmp_HeaderLenght.setProperty("value", 5)
        self.spinBox_icmp_HeaderLenght.setDisplayIntegerBase(10)
        self.spinBox_icmp_HeaderLenght.setObjectName("spinBox_icmp_HeaderLenght")
        self.horizontalLayout_46.addWidget(self.spinBox_icmp_HeaderLenght)
        self.verticalLayout_9.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_icmp_ToS = QtWidgets.QLabel(self.icmp)
        self.label_icmp_ToS.setObjectName("label_icmp_ToS")
        self.horizontalLayout_47.addWidget(self.label_icmp_ToS)
        self.spinBox_icmp_ToS = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_ToS.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_ToS.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_ToS.setWhatsThis("")
        self.spinBox_icmp_ToS.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_ToS.setSuffix("")
        self.spinBox_icmp_ToS.setMinimum(0)
        self.spinBox_icmp_ToS.setMaximum(255)
        self.spinBox_icmp_ToS.setDisplayIntegerBase(10)
        self.spinBox_icmp_ToS.setObjectName("spinBox_icmp_ToS")
        self.horizontalLayout_47.addWidget(self.spinBox_icmp_ToS)
        self.verticalLayout_9.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_icmp_TotalLength = QtWidgets.QLabel(self.icmp)
        self.label_icmp_TotalLength.setObjectName("label_icmp_TotalLength")
        self.horizontalLayout_49.addWidget(self.label_icmp_TotalLength)
        self.spinBox_icmp_TotalLenght = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_TotalLenght.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_TotalLenght.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_TotalLenght.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_TotalLenght.setSuffix("")
        self.spinBox_icmp_TotalLenght.setMinimum(0)
        self.spinBox_icmp_TotalLenght.setMaximum(65535)
        self.spinBox_icmp_TotalLenght.setProperty("value", 20)
        self.spinBox_icmp_TotalLenght.setDisplayIntegerBase(10)
        self.spinBox_icmp_TotalLenght.setObjectName("spinBox_icmp_TotalLenght")
        self.horizontalLayout_49.addWidget(self.spinBox_icmp_TotalLenght)
        self.verticalLayout_9.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_icmp_Identifier_2 = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Identifier_2.setObjectName("label_icmp_Identifier_2")
        self.horizontalLayout_50.addWidget(self.label_icmp_Identifier_2)
        self.spinBox_icmp_Identifier = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_Identifier.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_Identifier.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_Identifier.setWhatsThis("")
        self.spinBox_icmp_Identifier.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_Identifier.setSuffix("")
        self.spinBox_icmp_Identifier.setMaximum(65535)
        self.spinBox_icmp_Identifier.setProperty("value", 0)
        self.spinBox_icmp_Identifier.setDisplayIntegerBase(10)
        self.spinBox_icmp_Identifier.setObjectName("spinBox_icmp_Identifier")
        self.horizontalLayout_50.addWidget(self.spinBox_icmp_Identifier)
        self.verticalLayout_9.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_icmp_Flags = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Flags.setObjectName("label_icmp_Flags")
        self.horizontalLayout_51.addWidget(self.label_icmp_Flags)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.checkBox_icmp_Res = QtWidgets.QCheckBox(self.icmp)
        self.checkBox_icmp_Res.setObjectName("checkBox_icmp_Res")
        self.horizontalLayout_52.addWidget(self.checkBox_icmp_Res)
        self.checkBox_icmp_DF = QtWidgets.QCheckBox(self.icmp)
        self.checkBox_icmp_DF.setObjectName("checkBox_icmp_DF")
        self.horizontalLayout_52.addWidget(self.checkBox_icmp_DF)
        self.checkBox_icmp_MF = QtWidgets.QCheckBox(self.icmp)
        self.checkBox_icmp_MF.setObjectName("checkBox_icmp_MF")
        self.horizontalLayout_52.addWidget(self.checkBox_icmp_MF)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_52)
        self.verticalLayout_9.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_icmp_FragmentOffset = QtWidgets.QLabel(self.icmp)
        self.label_icmp_FragmentOffset.setObjectName("label_icmp_FragmentOffset")
        self.horizontalLayout_53.addWidget(self.label_icmp_FragmentOffset)
        self.spinBox_icmp_FragmentOffset = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_FragmentOffset.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_FragmentOffset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_FragmentOffset.setWhatsThis("")
        self.spinBox_icmp_FragmentOffset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_FragmentOffset.setSuffix("")
        self.spinBox_icmp_FragmentOffset.setMaximum(8191)
        self.spinBox_icmp_FragmentOffset.setProperty("value", 0)
        self.spinBox_icmp_FragmentOffset.setDisplayIntegerBase(10)
        self.spinBox_icmp_FragmentOffset.setObjectName("spinBox_icmp_FragmentOffset")
        self.horizontalLayout_53.addWidget(self.spinBox_icmp_FragmentOffset)
        self.verticalLayout_9.addLayout(self.horizontalLayout_53)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_icmp_TTL = QtWidgets.QLabel(self.icmp)
        self.label_icmp_TTL.setObjectName("label_icmp_TTL")
        self.horizontalLayout_54.addWidget(self.label_icmp_TTL)
        self.spinBox_icmp_TTL = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_TTL.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_TTL.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_TTL.setWhatsThis("")
        self.spinBox_icmp_TTL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_TTL.setSuffix("")
        self.spinBox_icmp_TTL.setMaximum(255)
        self.spinBox_icmp_TTL.setProperty("value", 64)
        self.spinBox_icmp_TTL.setDisplayIntegerBase(10)
        self.spinBox_icmp_TTL.setObjectName("spinBox_icmp_TTL")
        self.horizontalLayout_54.addWidget(self.spinBox_icmp_TTL)
        self.verticalLayout_10.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_icmp_Protocol = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Protocol.setObjectName("label_icmp_Protocol")
        self.horizontalLayout_55.addWidget(self.label_icmp_Protocol)
        self.spinBox_icmp_Protocol = QtWidgets.QSpinBox(self.icmp)
        self.spinBox_icmp_Protocol.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_icmp_Protocol.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_icmp_Protocol.setWhatsThis("")
        self.spinBox_icmp_Protocol.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_icmp_Protocol.setSuffix("")
        self.spinBox_icmp_Protocol.setMaximum(255)
        self.spinBox_icmp_Protocol.setProperty("value", 1)
        self.spinBox_icmp_Protocol.setDisplayIntegerBase(10)
        self.spinBox_icmp_Protocol.setObjectName("spinBox_icmp_Protocol")
        self.horizontalLayout_55.addWidget(self.spinBox_icmp_Protocol)
        self.verticalLayout_10.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_icmp_Checksum_2 = QtWidgets.QLabel(self.icmp)
        self.label_icmp_Checksum_2.setObjectName("label_icmp_Checksum_2")
        self.horizontalLayout_56.addWidget(self.label_icmp_Checksum_2)
        self.lineEdit_icmp_Checksum_2 = QtWidgets.QLineEdit(self.icmp)
        self.lineEdit_icmp_Checksum_2.setObjectName("lineEdit_icmp_Checksum_2")
        self.horizontalLayout_56.addWidget(self.lineEdit_icmp_Checksum_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_icmp_SRCIP = QtWidgets.QLabel(self.icmp)
        self.label_icmp_SRCIP.setObjectName("label_icmp_SRCIP")
        self.horizontalLayout_57.addWidget(self.label_icmp_SRCIP)
        self.lineEdit_icmp_SRCIP = QtWidgets.QLineEdit(self.icmp)
        self.lineEdit_icmp_SRCIP.setClearButtonEnabled(False)
        self.lineEdit_icmp_SRCIP.setObjectName("lineEdit_icmp_SRCIP")
        self.horizontalLayout_57.addWidget(self.lineEdit_icmp_SRCIP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_icmp_DSTIP = QtWidgets.QLabel(self.icmp)
        self.label_icmp_DSTIP.setObjectName("label_icmp_DSTIP")
        self.horizontalLayout_58.addWidget(self.label_icmp_DSTIP)
        self.lineEdit_icmp_DSTIP = QtWidgets.QLineEdit(self.icmp)
        self.lineEdit_icmp_DSTIP.setClearButtonEnabled(False)
        self.lineEdit_icmp_DSTIP.setObjectName("lineEdit_icmp_DSTIP")
        self.horizontalLayout_58.addWidget(self.lineEdit_icmp_DSTIP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_58)
        self.gridLayout_10.addLayout(self.verticalLayout_10, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.tab_L3_Widget.addTab(self.icmp, "")
        self.horizontalLayout_3.addWidget(self.tab_L3_Widget)
        self.tab_L2_Widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_L2_Widget.setObjectName("tab_L2_Widget")
        self.mac = QtWidgets.QWidget()
        self.mac.setObjectName("mac")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.mac)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_mac_SRCMAC = QtWidgets.QLabel(self.mac)
        self.label_mac_SRCMAC.setObjectName("label_mac_SRCMAC")
        self.horizontalLayout_67.addWidget(self.label_mac_SRCMAC)
        self.lineEdit_mac_SRCMAC = QtWidgets.QLineEdit(self.mac)
        self.lineEdit_mac_SRCMAC.setClearButtonEnabled(False)
        self.lineEdit_mac_SRCMAC.setObjectName("lineEdit_mac_SRCMAC")
        self.horizontalLayout_67.addWidget(self.lineEdit_mac_SRCMAC)
        self.verticalLayout_3.addLayout(self.horizontalLayout_67)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_mac_DSTMAC = QtWidgets.QLabel(self.mac)
        self.label_mac_DSTMAC.setObjectName("label_mac_DSTMAC")
        self.horizontalLayout_68.addWidget(self.label_mac_DSTMAC)
        self.lineEdit_mac_DSTMAC = QtWidgets.QLineEdit(self.mac)
        self.lineEdit_mac_DSTMAC.setClearButtonEnabled(False)
        self.lineEdit_mac_DSTMAC.setObjectName("lineEdit_mac_DSTMAC")
        self.horizontalLayout_68.addWidget(self.lineEdit_mac_DSTMAC)
        self.verticalLayout_3.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_mac_Data = QtWidgets.QLabel(self.mac)
        self.label_mac_Data.setEnabled(True)
        self.label_mac_Data.setObjectName("label_mac_Data")
        self.horizontalLayout_42.addWidget(self.label_mac_Data)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plainTextEdit_mac_Data = QtWidgets.QPlainTextEdit(self.mac)
        self.plainTextEdit_mac_Data.setEnabled(True)
        self.plainTextEdit_mac_Data.setObjectName("plainTextEdit_mac_Data")
        self.verticalLayout_5.addWidget(self.plainTextEdit_mac_Data)
        self.pushButton_5 = QtWidgets.QPushButton(self.mac)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_5.addWidget(self.pushButton_5)
        self.horizontalLayout_42.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_mac_Checksum = QtWidgets.QLabel(self.mac)
        self.label_mac_Checksum.setObjectName("label_mac_Checksum")
        self.horizontalLayout_69.addWidget(self.label_mac_Checksum)
        self.lineEdit_mac_Checksum = QtWidgets.QLineEdit(self.mac)
        self.lineEdit_mac_Checksum.setObjectName("lineEdit_mac_Checksum")
        self.horizontalLayout_69.addWidget(self.lineEdit_mac_Checksum)
        self.verticalLayout_3.addLayout(self.horizontalLayout_69)
        self.gridLayout_11.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tab_L2_Widget.addTab(self.mac, "")
        self.horizontalLayout_3.addWidget(self.tab_L2_Widget)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        PacketSender.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(PacketSender)
        self.statusBar.setObjectName("statusBar")
        PacketSender.setStatusBar(self.statusBar)

        self.retranslateUi(PacketSender)
        self.tab_L4_Widget.setCurrentIndex(1)
        self.tab_L3_Widget.setCurrentIndex(1)
        self.tab_L2_Widget.setCurrentIndex(0)
        self.tab_L4_Widget.currentChanged['int'].connect(self.spinBox_ipv4_Protocol.setProto)
        self.checkBox_tcp_Res1.clicked['bool'].connect(PacketSender.tcpRes1Changed)
        self.checkBox_tcp_Res2.clicked['bool'].connect(PacketSender.tcpRes2Changed)
        self.checkBox_tcp_Res3.clicked['bool'].connect(PacketSender.tcpRes3Changed)
        self.checkBox_tcp_Res4.clicked['bool'].connect(PacketSender.tcpRes4Changed)
        self.checkBox_tcp_CWR.clicked['bool'].connect(PacketSender.tcpCWRChanged)
        self.checkBox_tcp_ECE.clicked['bool'].connect(PacketSender.tcpECEChanged)
        self.checkBox_tcp_URG.clicked['bool'].connect(PacketSender.tcpURGChanged)
        self.checkBox_tcp_ACK.clicked['bool'].connect(PacketSender.tcpACKChanged)
        self.checkBox_tcp_PSH.clicked['bool'].connect(PacketSender.tcpPSHChanged)
        self.checkBox_tcp_RST.clicked['bool'].connect(PacketSender.tcpRSTChanged)
        self.checkBox_tcp_SYN.clicked['bool'].connect(PacketSender.tcpSYNChanged)
        self.checkBox_tcp_FIN.clicked['bool'].connect(PacketSender.tcpFINChanged)
        self.lineEdit_tcp_Checksum.returnPressed.connect(PacketSender.tcpChecksumChanged)
        self.checkBox_tcp_Nops.clicked['bool'].connect(PacketSender.tcpOptionsAddNopsChanged)
        self.checkBox_tcp_Timestamp.clicked['bool'].connect(PacketSender.tcpOptionsAddTimestampChanged)
        self.sendButton.clicked.connect(PacketSender.sendBtnClicked)
        self.lineEdit_udp_Checksum.returnPressed.connect(PacketSender.udpChecksumChanged)
        self.plainTextEdit_udp_Data.textChanged.connect(PacketSender.udpDataChanged)
        self.checkBox_ipv4_Res.clicked['bool'].connect(PacketSender.ipv4ResChanged)
        self.checkBox_ipv4_DF.clicked['bool'].connect(PacketSender.ipv4DFChanged)
        self.checkBox_ipv4_MF.clicked['bool'].connect(PacketSender.ipv4MFChanged)
        self.lineEdit_ipv4_Checksum.returnPressed.connect(PacketSender.ipv4ChecksumChanged)
        self.lineEdit_ipv4_SRCIP.returnPressed.connect(PacketSender.ipv4SRCIPChanged)
        self.lineEdit_ipv4_DSTIP.returnPressed.connect(PacketSender.ipv4DSTIPChanged)
        self.checkBox_ipv4_options_Copied.clicked['bool'].connect(PacketSender.ipv4OptionsCopiedChanged)
        self.spinBox_ipv4_options_Class.editingFinished.connect(PacketSender.ipv4OptionsClassChanged)
        self.spinBox_ipv4_options_Number.editingFinished.connect(PacketSender.ipv4OptionsNumberChanged)
        self.spinBox_ipv4_options_Length.editingFinished.connect(PacketSender.ipv4OptionsLengthChanged)
        self.plainTextEdit_ipv4_options_Data.textChanged.connect(PacketSender.ipv4OptionsDataChanged)
        self.plainTextEdit_ipv4_Data.textChanged.connect(PacketSender.ipv4DataChanged)
        self.spinBox_icmp_Code.editingFinished.connect(PacketSender.icmpCodeChanged)
        self.lineEdit_icmp_Checksum.returnPressed.connect(PacketSender.icmpChecksumChanged)
        self.spinBox_ipv4_Version.valueChanged['int'].connect(self.spinBox_icmp_Version.setValue)
        self.spinBox_ipv4_IHL.valueChanged['int'].connect(self.spinBox_icmp_HeaderLenght.setValue)
        self.spinBox_ipv4_DSCP.valueChanged['int'].connect(self.spinBox_icmp_ToS.setValue)
        self.spinBox_ipv4_TotalLength.valueChanged['int'].connect(self.spinBox_icmp_TotalLenght.setValue)
        self.spinBox_ipv4_Identification.valueChanged['int'].connect(self.spinBox_icmp_Identifier.setValue)
        self.checkBox_ipv4_Res.clicked['bool'].connect(self.checkBox_icmp_Res.setChecked)
        self.checkBox_ipv4_DF.clicked['bool'].connect(self.checkBox_icmp_DF.setChecked)
        self.checkBox_ipv4_MF.clicked['bool'].connect(self.checkBox_icmp_MF.setChecked)
        self.spinBox_ipv4_FragmentOffset.valueChanged['int'].connect(self.spinBox_icmp_FragmentOffset.setValue)
        self.spinBox_ipv4_TTL.valueChanged['int'].connect(self.spinBox_icmp_TTL.setValue)
        self.spinBox_ipv4_Protocol.valueChanged['int'].connect(self.spinBox_icmp_Protocol.setValue)
        self.lineEdit_ipv4_Checksum.textChanged['QString'].connect(self.lineEdit_icmp_Checksum_2.setText)
        self.lineEdit_mac_SRCMAC.returnPressed.connect(PacketSender.macSRCMacChanged)
        self.lineEdit_mac_DSTMAC.returnPressed.connect(PacketSender.macDSTMacChanged)
        self.plainTextEdit_mac_Data.textChanged.connect(PacketSender.macDataChanged)
        self.lineEdit_mac_Checksum.returnPressed.connect(PacketSender.macChecksumChanged)
        self.spinBox_icmp_Version.valueChanged['int'].connect(self.spinBox_ipv4_Version.setValue)
        self.spinBox_icmp_HeaderLenght.valueChanged['int'].connect(self.spinBox_ipv4_IHL.setValue)
        self.spinBox_icmp_TotalLenght.valueChanged['int'].connect(self.spinBox_ipv4_TotalLength.setValue)
        self.spinBox_icmp_Identifier.valueChanged['int'].connect(self.spinBox_ipv4_Identification.setValue)
        self.checkBox_icmp_Res.clicked['bool'].connect(self.checkBox_ipv4_Res.setChecked)
        self.checkBox_icmp_DF.clicked['bool'].connect(self.checkBox_ipv4_DF.setChecked)
        self.checkBox_icmp_MF.clicked['bool'].connect(self.checkBox_ipv4_MF.setChecked)
        self.spinBox_icmp_FragmentOffset.valueChanged['int'].connect(self.spinBox_ipv4_FragmentOffset.setValue)
        self.spinBox_icmp_TTL.valueChanged['int'].connect(self.spinBox_ipv4_TTL.setValue)
        self.spinBox_icmp_Protocol.valueChanged['int'].connect(self.spinBox_ipv4_Protocol.setValue)
        self.lineEdit_icmp_Checksum.textChanged['QString'].connect(self.lineEdit_ipv4_Checksum.setText)
        self.lineEdit_icmp_DSTIP.returnPressed.connect(PacketSender.ipv4DSTIPChanged)
        self.lineEdit_icmp_SRCIP.returnPressed.connect(PacketSender.ipv4SRCIPChanged)
        self.plainTextEdit_tcp_Data.textChanged.connect(PacketSender.tcpDataChanged)
        self.pushButton_Bottom_Save.clicked.connect(PacketSender.saveBtnClicked)
        self.pushButton_Bottom_ToQueue.clicked.connect(PacketSender.toQueueBtnClicked)
        self.pushButton_Bottom_RefreshAll.clicked.connect(PacketSender.refreshAllBtnClicked)
        self.listWidget_Bottom_Packets.itemDoubleClicked['QListWidgetItem*'].connect(PacketSender.loadPacket)
        QtCore.QMetaObject.connectSlotsByName(PacketSender)

    def retranslateUi(self, PacketSender):
        _translate = QtCore.QCoreApplication.translate
        PacketSender.setWindowTitle(_translate("PacketSender", "MainWindow"))
        self.label_3.setText(_translate("PacketSender", "Interface:"))
        self.pushButton_Bottom_Save.setText(_translate("PacketSender", "Save"))
        self.pushButton_2.setText(_translate("PacketSender", "Delete"))
        self.pushButton_Bottom_Packets_Refresh.setText(_translate("PacketSender", "Refresh"))
        self.pushButton_Bottom_ToQueue.setText(_translate("PacketSender", "To queue"))
        self.pushButton_Bottom_Queue_Delete.setText(_translate("PacketSender", "Delete"))
        self.sendButton.setText(_translate("PacketSender", "Send"))
        self.label_2.setText(_translate("PacketSender", "ms"))
        self.label_icmp_DF.setText(_translate("PacketSender", "times every "))
        self.pushButton_Bottom_RefreshAll.setText(_translate("PacketSender", "Refresh All"))
        self.label_tcp_SRCPort.setText(_translate("PacketSender", "SRC Port"))
        self.spinBox_tcp_SRCPort.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_tcp_DSTPort.setText(_translate("PacketSender", "DST Port"))
        self.spinBox_tcp_DSTPort.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_tcp_SEQNum.setText(_translate("PacketSender", "SEQ Number"))
        self.spinBox_tcp_SEQ.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_tcp_ACKNum.setText(_translate("PacketSender", "ACK Number"))
        self.spinBox_tcp_ACK.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_tcp_DataOffset.setText(_translate("PacketSender", "Data Offset"))
        self.spinBox_tcp_DataOffset.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_tcp_ReservetBits.setText(_translate("PacketSender", "Reserved bits"))
        self.checkBox_tcp_Res1.setText(_translate("PacketSender", "Res 1"))
        self.checkBox_tcp_Res2.setText(_translate("PacketSender", "Res 2"))
        self.checkBox_tcp_Res3.setText(_translate("PacketSender", "Res 3"))
        self.checkBox_tcp_Res4.setText(_translate("PacketSender", "Res 4"))
        self.checkBox_tcp_CWR.setText(_translate("PacketSender", "CWR"))
        self.checkBox_tcp_ECE.setText(_translate("PacketSender", "ECE"))
        self.label_tcp_ControlBits.setText(_translate("PacketSender", "Control bits"))
        self.checkBox_tcp_URG.setText(_translate("PacketSender", "URG"))
        self.checkBox_tcp_ACK.setText(_translate("PacketSender", "ACK"))
        self.checkBox_tcp_PSH.setText(_translate("PacketSender", "PSH"))
        self.checkBox_tcp_RST.setText(_translate("PacketSender", "RST"))
        self.checkBox_tcp_SYN.setText(_translate("PacketSender", "SYN"))
        self.checkBox_tcp_FIN.setText(_translate("PacketSender", "FIN"))
        self.label_tcp_WIN.setText(_translate("PacketSender", "Window size"))
        self.spinBox_tcp_WIN.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_tcp_Checksum.setText(_translate("PacketSender", "Checksum"))
        self.lineEdit_tcp_Checksum.setPlaceholderText(_translate("PacketSender", "0...65535"))
        self.label_tcp_UrgentPointers.setText(_translate("PacketSender", "Urgent pointers"))
        self.spinBox_tcp_Urgent.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_tcp_Options.setText(_translate("PacketSender", "Options"))
        self.checkBox_tcp_Nops.setText(_translate("PacketSender", "Add two NOPs (16bits)"))
        self.checkBox_tcp_Timestamp.setText(_translate("PacketSender", "Add Timestamp (80bits)"))
        self.label_tcp_Data.setText(_translate("PacketSender", "Data"))
        self.pushButton_6.setText(_translate("PacketSender", "Open file"))
        self.tab_L4_Widget.setTabText(self.tab_L4_Widget.indexOf(self.tcp), _translate("PacketSender", "TCP"))
        self.label_udp_SRCPort.setText(_translate("PacketSender", "SRC Port"))
        self.spinBox_udp_SRCPort.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_udp_DSTPort.setText(_translate("PacketSender", "DST Port"))
        self.spinBox_udp_DSTPort.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_udp_length.setText(_translate("PacketSender", "Length"))
        self.spinBox_udp_Length.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_udp_checksum.setText(_translate("PacketSender", "Checksum"))
        self.lineEdit_udp_Checksum.setPlaceholderText(_translate("PacketSender", "0...65535"))
        self.label_udp_Data.setText(_translate("PacketSender", "Data"))
        self.pushButton_7.setText(_translate("PacketSender", "Open file"))
        self.tab_L4_Widget.setTabText(self.tab_L4_Widget.indexOf(self.udp), _translate("PacketSender", "UDP"))
        self.label_ipv4_TTL.setText(_translate("PacketSender", "TTL"))
        self.spinBox_ipv4_TTL.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_ipv4_Protocol.setText(_translate("PacketSender", "Protocol"))
        self.spinBox_ipv4_Protocol.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_ipv4_Checksum.setText(_translate("PacketSender", "Checksum"))
        self.lineEdit_ipv4_Checksum.setPlaceholderText(_translate("PacketSender", "0...65535"))
        self.label_ipv4_SRCIP.setText(_translate("PacketSender", "SRC IP"))
        self.lineEdit_ipv4_SRCIP.setInputMask(_translate("PacketSender", "000.000.000.000;_"))
        self.lineEdit_ipv4_SRCIP.setText(_translate("PacketSender", "..."))
        self.label_ipv4_DSTIP.setText(_translate("PacketSender", "DST IP"))
        self.lineEdit_ipv4_DSTIP.setInputMask(_translate("PacketSender", "000.000.000.000;_"))
        self.lineEdit_ipv4_DSTIP.setText(_translate("PacketSender", "..."))
        self.label_ipv4_Option.setText(_translate("PacketSender", "Options"))
        self.checkBox_ipv4_options_Copied.setText(_translate("PacketSender", "Copied"))
        self.label_ipv4_options_Class.setText(_translate("PacketSender", "Class"))
        self.spinBox_ipv4_options_Class.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_ipv4_options_Number.setText(_translate("PacketSender", "Number"))
        self.spinBox_ipv4_options_Number.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_ipv4_options_Length.setText(_translate("PacketSender", "Length"))
        self.spinBox_ipv4_options_Length.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_ipv4_options_Data.setText(_translate("PacketSender", "Data"))
        self.label_ipv4_Data.setText(_translate("PacketSender", "Data"))
        self.pushButton.setText(_translate("PacketSender", "Refresh"))
        self.label_ipv4_Version.setText(_translate("PacketSender", "Version"))
        self.spinBox_ipv4_Version.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_ipv4_IHL.setText(_translate("PacketSender", "IHL"))
        self.spinBox_ipv4_IHL.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBox_ipv4_IHL.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 5 in standard</p><p><br/></p><p><br/></p></body></html>"))
        self.label_ipv4_DSCP.setText(_translate("PacketSender", "DSCP"))
        self.spinBox_ipv4_DSCP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_ipv4_ECN.setText(_translate("PacketSender", "ECN"))
        self.spinBox_ipv4_ECN.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_ipv4_TotalLength.setText(_translate("PacketSender", "Total length"))
        self.spinBox_ipv4_TotalLength.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBox_ipv4_TotalLength.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 20 in standard</p><p><br/></p></body></html>"))
        self.label_ipv4_Identification.setText(_translate("PacketSender", "Identification"))
        self.spinBox_ipv4_Identification.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_ipv4_Flags.setText(_translate("PacketSender", "Flags"))
        self.checkBox_ipv4_Res.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Must be 0</p><p><br/></p></body></html>"))
        self.checkBox_ipv4_Res.setText(_translate("PacketSender", "Res"))
        self.checkBox_ipv4_DF.setText(_translate("PacketSender", "DF"))
        self.checkBox_ipv4_MF.setText(_translate("PacketSender", "MF"))
        self.label_ipv4_FragmentOffset.setText(_translate("PacketSender", "Fragment offset"))
        self.spinBox_ipv4_FragmentOffset.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.tab_L3_Widget.setTabText(self.tab_L3_Widget.indexOf(self.ipv4), _translate("PacketSender", "IPv4"))
        self.label_icmp_Type.setText(_translate("PacketSender", "Type"))
        self.spinBox_icmp_Type.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_icmp_Code.setText(_translate("PacketSender", "Code"))
        self.spinBox_icmp_Code.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_icmp_Checksum.setText(_translate("PacketSender", "ICMP Checksum"))
        self.label_icmp_ID.setText(_translate("PacketSender", "ID"))
        self.spinBox_icmp_id.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_icmp_seq_number.setText(_translate("PacketSender", "Seq number"))
        self.spinBox_icmp_seqNum.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_udp_Data_2.setText(_translate("PacketSender", "Data"))
        self.pushButton_8.setText(_translate("PacketSender", "Open file"))
        self.label_icmp_Version.setText(_translate("PacketSender", "Version"))
        self.spinBox_icmp_Version.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_icmp_HeaderLenght.setText(_translate("PacketSender", "Header Length"))
        self.spinBox_icmp_HeaderLenght.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBox_icmp_HeaderLenght.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 5 in standard</p><p><br/></p><p><br/></p></body></html>"))
        self.label_icmp_ToS.setText(_translate("PacketSender", "Type of Service"))
        self.spinBox_icmp_ToS.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_icmp_TotalLength.setText(_translate("PacketSender", "Total length"))
        self.spinBox_icmp_TotalLenght.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBox_icmp_TotalLenght.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 20 in standard</p><p><br/></p></body></html>"))
        self.label_icmp_Identifier_2.setText(_translate("PacketSender", "Identifier"))
        self.spinBox_icmp_Identifier.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_icmp_Flags.setText(_translate("PacketSender", "Flags"))
        self.checkBox_icmp_Res.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Must be 0</p><p><br/></p></body></html>"))
        self.checkBox_icmp_Res.setText(_translate("PacketSender", "Res"))
        self.checkBox_icmp_DF.setText(_translate("PacketSender", "DF"))
        self.checkBox_icmp_MF.setText(_translate("PacketSender", "MF"))
        self.label_icmp_FragmentOffset.setText(_translate("PacketSender", "Fragment offset"))
        self.spinBox_icmp_FragmentOffset.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_icmp_TTL.setText(_translate("PacketSender", "TTL"))
        self.spinBox_icmp_TTL.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_icmp_Protocol.setText(_translate("PacketSender", "Protocol"))
        self.spinBox_icmp_Protocol.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_icmp_Checksum_2.setText(_translate("PacketSender", "Checksum"))
        self.label_icmp_SRCIP.setText(_translate("PacketSender", "SRC IP"))
        self.lineEdit_icmp_SRCIP.setInputMask(_translate("PacketSender", "000.000.000.000;_"))
        self.lineEdit_icmp_SRCIP.setText(_translate("PacketSender", "..."))
        self.label_icmp_DSTIP.setText(_translate("PacketSender", "DST IP"))
        self.lineEdit_icmp_DSTIP.setInputMask(_translate("PacketSender", "000.000.000.000;_"))
        self.lineEdit_icmp_DSTIP.setText(_translate("PacketSender", "..."))
        self.tab_L3_Widget.setTabText(self.tab_L3_Widget.indexOf(self.icmp), _translate("PacketSender", "ICMP"))
        self.label_mac_SRCMAC.setText(_translate("PacketSender", "SRC MAC"))
        self.lineEdit_mac_SRCMAC.setInputMask(_translate("PacketSender", "HH:HH:HH:HH:HH:HH;_"))
        self.label_mac_DSTMAC.setText(_translate("PacketSender", "DST MAC"))
        self.lineEdit_mac_DSTMAC.setInputMask(_translate("PacketSender", "HH:HH:HH:HH:HH:HH;_"))
        self.label_mac_Data.setText(_translate("PacketSender", "Data"))
        self.pushButton_5.setText(_translate("PacketSender", "Refresh"))
        self.label_mac_Checksum.setText(_translate("PacketSender", "Checksum"))
        self.lineEdit_mac_Checksum.setPlaceholderText(_translate("PacketSender", "0...65535"))
        self.tab_L2_Widget.setTabText(self.tab_L2_Widget.indexOf(self.mac), _translate("PacketSender", "MAC"))
from psIpProtoSpinBox import PSIpProtoSpinBox
from qlistwidgetpacketsqueue import QListWidgetPacketsQueue
from qlistwidgetsavedpackets import QListWidgetSavedPackets
