# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PacketSender(object):
    def setupUi(self, PacketSender):
        PacketSender.setObjectName("PacketSender")
        PacketSender.resize(1440, 794)
        PacketSender.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(PacketSender)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tab_L4_Widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_L4_Widget.setObjectName("tab_L4_Widget")
        self.tcp = QtWidgets.QWidget()
        self.tcp.setObjectName("tcp")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tcp)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.tcp)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.spinBoxSrcPort_TCP = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxSrcPort_TCP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxSrcPort_TCP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxSrcPort_TCP.setWhatsThis("")
        self.spinBoxSrcPort_TCP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxSrcPort_TCP.setSuffix("")
        self.spinBoxSrcPort_TCP.setMaximum(65535)
        self.spinBoxSrcPort_TCP.setDisplayIntegerBase(10)
        self.spinBoxSrcPort_TCP.setObjectName("spinBoxSrcPort_TCP")
        self.horizontalLayout_9.addWidget(self.spinBoxSrcPort_TCP)
        self.gridLayout_8.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.tcp)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.spinBoxDstPort_TCP = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxDstPort_TCP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxDstPort_TCP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxDstPort_TCP.setWhatsThis("")
        self.spinBoxDstPort_TCP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDstPort_TCP.setSuffix("")
        self.spinBoxDstPort_TCP.setMaximum(65535)
        self.spinBoxDstPort_TCP.setProperty("value", 8000)
        self.spinBoxDstPort_TCP.setDisplayIntegerBase(10)
        self.spinBoxDstPort_TCP.setObjectName("spinBoxDstPort_TCP")
        self.horizontalLayout_8.addWidget(self.spinBoxDstPort_TCP)
        self.gridLayout_8.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.tcp)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.spinBoxSEQ = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxSEQ.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxSEQ.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxSEQ.setWhatsThis("")
        self.spinBoxSEQ.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxSEQ.setSuffix("")
        self.spinBoxSEQ.setMinimum(-2147483647)
        self.spinBoxSEQ.setMaximum(2147483646)
        self.spinBoxSEQ.setDisplayIntegerBase(10)
        self.spinBoxSEQ.setObjectName("spinBoxSEQ")
        self.horizontalLayout_10.addWidget(self.spinBoxSEQ)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.tcp)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.spinBoxACK = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxACK.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxACK.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxACK.setWhatsThis("")
        self.spinBoxACK.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxACK.setSuffix("")
        self.spinBoxACK.setMinimum(-2147483647)
        self.spinBoxACK.setMaximum(2147483646)
        self.spinBoxACK.setDisplayIntegerBase(10)
        self.spinBoxACK.setObjectName("spinBoxACK")
        self.horizontalLayout_11.addWidget(self.spinBoxACK)
        self.gridLayout_8.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.tcp)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.spinBoxDataOffset = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxDataOffset.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxDataOffset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxDataOffset.setWhatsThis("")
        self.spinBoxDataOffset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDataOffset.setSuffix("")
        self.spinBoxDataOffset.setMinimum(0)
        self.spinBoxDataOffset.setMaximum(15)
        self.spinBoxDataOffset.setDisplayIntegerBase(10)
        self.spinBoxDataOffset.setObjectName("spinBoxDataOffset")
        self.horizontalLayout_12.addWidget(self.spinBoxDataOffset)
        self.gridLayout_8.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.tcp)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_Reserved1 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_Reserved1.setObjectName("checkBox_Reserved1")
        self.horizontalLayout_2.addWidget(self.checkBox_Reserved1)
        self.checkBox_Reserved2 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_Reserved2.setObjectName("checkBox_Reserved2")
        self.horizontalLayout_2.addWidget(self.checkBox_Reserved2)
        self.checkBox_Reserved3 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_Reserved3.setObjectName("checkBox_Reserved3")
        self.horizontalLayout_2.addWidget(self.checkBox_Reserved3)
        self.checkBox_Reserved4 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_Reserved4.setObjectName("checkBox_Reserved4")
        self.horizontalLayout_2.addWidget(self.checkBox_Reserved4)
        self.checkBox_Reserved5 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_Reserved5.setObjectName("checkBox_Reserved5")
        self.horizontalLayout_2.addWidget(self.checkBox_Reserved5)
        self.checkBox_Reserved6 = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_Reserved6.setObjectName("checkBox_Reserved6")
        self.horizontalLayout_2.addWidget(self.checkBox_Reserved6)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.tcp)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_ = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_.setObjectName("checkBox_")
        self.horizontalLayout_4.addWidget(self.checkBox_)
        self.checkBox_ACK = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_ACK.setObjectName("checkBox_ACK")
        self.horizontalLayout_4.addWidget(self.checkBox_ACK)
        self.checkBox_PSH = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_PSH.setObjectName("checkBox_PSH")
        self.horizontalLayout_4.addWidget(self.checkBox_PSH)
        self.checkBox_RST = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_RST.setObjectName("checkBox_RST")
        self.horizontalLayout_4.addWidget(self.checkBox_RST)
        self.checkBox_SYN = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_SYN.setObjectName("checkBox_SYN")
        self.horizontalLayout_4.addWidget(self.checkBox_SYN)
        self.checkBox_FIN = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_FIN.setObjectName("checkBox_FIN")
        self.horizontalLayout_4.addWidget(self.checkBox_FIN)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_4)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.tcp)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.spinBoxWIN = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxWIN.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxWIN.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxWIN.setWhatsThis("")
        self.spinBoxWIN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxWIN.setSuffix("")
        self.spinBoxWIN.setMinimum(0)
        self.spinBoxWIN.setMaximum(2147483646)
        self.spinBoxWIN.setDisplayIntegerBase(10)
        self.spinBoxWIN.setObjectName("spinBoxWIN")
        self.horizontalLayout_15.addWidget(self.spinBoxWIN)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 7, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.tcp)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.spinBoxChecksum_TCP = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxChecksum_TCP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxChecksum_TCP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxChecksum_TCP.setWhatsThis("")
        self.spinBoxChecksum_TCP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxChecksum_TCP.setSuffix("")
        self.spinBoxChecksum_TCP.setMinimum(0)
        self.spinBoxChecksum_TCP.setMaximum(2147483646)
        self.spinBoxChecksum_TCP.setDisplayIntegerBase(10)
        self.spinBoxChecksum_TCP.setObjectName("spinBoxChecksum_TCP")
        self.horizontalLayout_16.addWidget(self.spinBoxChecksum_TCP)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 8, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.tcp)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.spinBoxUrgent = QtWidgets.QSpinBox(self.tcp)
        self.spinBoxUrgent.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxUrgent.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxUrgent.setWhatsThis("")
        self.spinBoxUrgent.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxUrgent.setSuffix("")
        self.spinBoxUrgent.setMinimum(0)
        self.spinBoxUrgent.setMaximum(2147483646)
        self.spinBoxUrgent.setDisplayIntegerBase(10)
        self.spinBoxUrgent.setObjectName("spinBoxUrgent")
        self.horizontalLayout_17.addWidget(self.spinBoxUrgent)
        self.gridLayout_8.addLayout(self.horizontalLayout_17, 9, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.tcp)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_NOPS = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_NOPS.setObjectName("checkBox_NOPS")
        self.verticalLayout_2.addWidget(self.checkBox_NOPS)
        self.checkBox_Timestamp = QtWidgets.QCheckBox(self.tcp)
        self.checkBox_Timestamp.setObjectName("checkBox_Timestamp")
        self.verticalLayout_2.addWidget(self.checkBox_Timestamp)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 10, 0, 1, 1)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_38 = QtWidgets.QLabel(self.tcp)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_43.addWidget(self.label_38)
        self.plainTextEdit_TCP_Data = QtWidgets.QPlainTextEdit(self.tcp)
        self.plainTextEdit_TCP_Data.setObjectName("plainTextEdit_TCP_Data")
        self.horizontalLayout_43.addWidget(self.plainTextEdit_TCP_Data)
        self.gridLayout_8.addLayout(self.horizontalLayout_43, 11, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.tab_L4_Widget.addTab(self.tcp, "")
        self.udp = QtWidgets.QWidget()
        self.udp.setObjectName("udp")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.udp)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_34 = QtWidgets.QLabel(self.udp)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_39.addWidget(self.label_34)
        self.spinBoxSrcPort_UDP = QtWidgets.QSpinBox(self.udp)
        self.spinBoxSrcPort_UDP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxSrcPort_UDP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxSrcPort_UDP.setWhatsThis("")
        self.spinBoxSrcPort_UDP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxSrcPort_UDP.setSuffix("")
        self.spinBoxSrcPort_UDP.setMaximum(65535)
        self.spinBoxSrcPort_UDP.setDisplayIntegerBase(10)
        self.spinBoxSrcPort_UDP.setObjectName("spinBoxSrcPort_UDP")
        self.horizontalLayout_39.addWidget(self.spinBoxSrcPort_UDP)
        self.verticalLayout_6.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_33 = QtWidgets.QLabel(self.udp)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_38.addWidget(self.label_33)
        self.spinBoxDstPort_UDP = QtWidgets.QSpinBox(self.udp)
        self.spinBoxDstPort_UDP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxDstPort_UDP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxDstPort_UDP.setWhatsThis("")
        self.spinBoxDstPort_UDP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDstPort_UDP.setSuffix("")
        self.spinBoxDstPort_UDP.setMaximum(65535)
        self.spinBoxDstPort_UDP.setProperty("value", 8000)
        self.spinBoxDstPort_UDP.setDisplayIntegerBase(10)
        self.spinBoxDstPort_UDP.setObjectName("spinBoxDstPort_UDP")
        self.horizontalLayout_38.addWidget(self.spinBoxDstPort_UDP)
        self.verticalLayout_6.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_35 = QtWidgets.QLabel(self.udp)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_40.addWidget(self.label_35)
        self.spinBoxLength_UDP = QtWidgets.QSpinBox(self.udp)
        self.spinBoxLength_UDP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxLength_UDP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxLength_UDP.setWhatsThis("")
        self.spinBoxLength_UDP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxLength_UDP.setSuffix("")
        self.spinBoxLength_UDP.setMaximum(65535)
        self.spinBoxLength_UDP.setDisplayIntegerBase(10)
        self.spinBoxLength_UDP.setObjectName("spinBoxLength_UDP")
        self.horizontalLayout_40.addWidget(self.spinBoxLength_UDP)
        self.verticalLayout_6.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_36 = QtWidgets.QLabel(self.udp)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_41.addWidget(self.label_36)
        self.spinBoxChecksum_UDP = QtWidgets.QSpinBox(self.udp)
        self.spinBoxChecksum_UDP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxChecksum_UDP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxChecksum_UDP.setWhatsThis("")
        self.spinBoxChecksum_UDP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxChecksum_UDP.setSuffix("")
        self.spinBoxChecksum_UDP.setMaximum(65535)
        self.spinBoxChecksum_UDP.setDisplayIntegerBase(10)
        self.spinBoxChecksum_UDP.setObjectName("spinBoxChecksum_UDP")
        self.horizontalLayout_41.addWidget(self.spinBoxChecksum_UDP)
        self.verticalLayout_6.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_39 = QtWidgets.QLabel(self.udp)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_44.addWidget(self.label_39)
        self.plainTextEdit_UDP_Data_2 = QtWidgets.QPlainTextEdit(self.udp)
        self.plainTextEdit_UDP_Data_2.setObjectName("plainTextEdit_UDP_Data_2")
        self.horizontalLayout_44.addWidget(self.plainTextEdit_UDP_Data_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_44)
        self.gridLayout_7.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tab_L4_Widget.addTab(self.udp, "")
        self.horizontalLayout_3.addWidget(self.tab_L4_Widget)
        self.tab_L3_Widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_L3_Widget.setObjectName("tab_L3_Widget")
        self.ipv4 = QtWidgets.QWidget()
        self.ipv4.setObjectName("ipv4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ipv4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.ipv4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.spinBoxIPversion = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxIPversion.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIPversion.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIPversion.setWhatsThis("")
        self.spinBoxIPversion.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIPversion.setSuffix("")
        self.spinBoxIPversion.setMinimum(0)
        self.spinBoxIPversion.setMaximum(15)
        self.spinBoxIPversion.setProperty("value", 4)
        self.spinBoxIPversion.setDisplayIntegerBase(10)
        self.spinBoxIPversion.setObjectName("spinBoxIPversion")
        self.horizontalLayout_7.addWidget(self.spinBoxIPversion)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.ipv4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.spinBoxIHL = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxIHL.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIHL.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIHL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIHL.setSuffix("")
        self.spinBoxIHL.setMinimum(0)
        self.spinBoxIHL.setMaximum(15)
        self.spinBoxIHL.setProperty("value", 5)
        self.spinBoxIHL.setDisplayIntegerBase(10)
        self.spinBoxIHL.setObjectName("spinBoxIHL")
        self.horizontalLayout_19.addWidget(self.spinBoxIHL)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.ipv4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        self.spinBoxIDSCP = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxIDSCP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIDSCP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIDSCP.setWhatsThis("")
        self.spinBoxIDSCP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIDSCP.setSuffix("")
        self.spinBoxIDSCP.setMinimum(0)
        self.spinBoxIDSCP.setMaximum(63)
        self.spinBoxIDSCP.setDisplayIntegerBase(10)
        self.spinBoxIDSCP.setObjectName("spinBoxIDSCP")
        self.horizontalLayout_20.addWidget(self.spinBoxIDSCP)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.ipv4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_21.addWidget(self.label_18)
        self.spinBoxIECN = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxIECN.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIECN.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIECN.setWhatsThis("")
        self.spinBoxIECN.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIECN.setSuffix("")
        self.spinBoxIECN.setMinimum(0)
        self.spinBoxIECN.setMaximum(3)
        self.spinBoxIECN.setDisplayIntegerBase(10)
        self.spinBoxIECN.setObjectName("spinBoxIECN")
        self.horizontalLayout_21.addWidget(self.spinBoxIECN)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.ipv4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_22.addWidget(self.label_19)
        self.spinBoxTotalLenght = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxTotalLenght.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxTotalLenght.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxTotalLenght.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxTotalLenght.setSuffix("")
        self.spinBoxTotalLenght.setMinimum(0)
        self.spinBoxTotalLenght.setMaximum(65535)
        self.spinBoxTotalLenght.setProperty("value", 20)
        self.spinBoxTotalLenght.setDisplayIntegerBase(10)
        self.spinBoxTotalLenght.setObjectName("spinBoxTotalLenght")
        self.horizontalLayout_22.addWidget(self.spinBoxTotalLenght)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_21 = QtWidgets.QLabel(self.ipv4)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_25.addWidget(self.label_21)
        self.spinBoxIdentification = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxIdentification.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIdentification.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIdentification.setWhatsThis("")
        self.spinBoxIdentification.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIdentification.setSuffix("")
        self.spinBoxIdentification.setMaximum(65535)
        self.spinBoxIdentification.setProperty("value", 0)
        self.spinBoxIdentification.setDisplayIntegerBase(10)
        self.spinBoxIdentification.setObjectName("spinBoxIdentification")
        self.horizontalLayout_25.addWidget(self.spinBoxIdentification)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_20 = QtWidgets.QLabel(self.ipv4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_24.addWidget(self.label_20)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.checkBox_reserved = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_reserved.setObjectName("checkBox_reserved")
        self.horizontalLayout_23.addWidget(self.checkBox_reserved)
        self.checkBox_DF = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_DF.setObjectName("checkBox_DF")
        self.horizontalLayout_23.addWidget(self.checkBox_DF)
        self.checkBox_MF = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_MF.setObjectName("checkBox_MF")
        self.horizontalLayout_23.addWidget(self.checkBox_MF)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_23)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_22 = QtWidgets.QLabel(self.ipv4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_26.addWidget(self.label_22)
        self.spinBoxFragOffset = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxFragOffset.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxFragOffset.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxFragOffset.setWhatsThis("")
        self.spinBoxFragOffset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxFragOffset.setSuffix("")
        self.spinBoxFragOffset.setMaximum(8191)
        self.spinBoxFragOffset.setProperty("value", 0)
        self.spinBoxFragOffset.setDisplayIntegerBase(10)
        self.spinBoxFragOffset.setObjectName("spinBoxFragOffset")
        self.horizontalLayout_26.addWidget(self.spinBoxFragOffset)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_23 = QtWidgets.QLabel(self.ipv4)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_27.addWidget(self.label_23)
        self.spinBoxTTL = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxTTL.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxTTL.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxTTL.setWhatsThis("")
        self.spinBoxTTL.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxTTL.setSuffix("")
        self.spinBoxTTL.setMaximum(255)
        self.spinBoxTTL.setProperty("value", 64)
        self.spinBoxTTL.setDisplayIntegerBase(10)
        self.spinBoxTTL.setObjectName("spinBoxTTL")
        self.horizontalLayout_27.addWidget(self.spinBoxTTL)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_24 = QtWidgets.QLabel(self.ipv4)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_28.addWidget(self.label_24)
        self.spinBoxProtocol = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxProtocol.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxProtocol.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxProtocol.setWhatsThis("")
        self.spinBoxProtocol.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxProtocol.setSuffix("")
        self.spinBoxProtocol.setMaximum(255)
        self.spinBoxProtocol.setProperty("value", 6)
        self.spinBoxProtocol.setDisplayIntegerBase(10)
        self.spinBoxProtocol.setObjectName("spinBoxProtocol")
        self.horizontalLayout_28.addWidget(self.spinBoxProtocol)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_25 = QtWidgets.QLabel(self.ipv4)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_29.addWidget(self.label_25)
        self.spinBoxChecksum_IP = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxChecksum_IP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxChecksum_IP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxChecksum_IP.setWhatsThis("")
        self.spinBoxChecksum_IP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxChecksum_IP.setSuffix("")
        self.spinBoxChecksum_IP.setMaximum(65535)
        self.spinBoxChecksum_IP.setProperty("value", 0)
        self.spinBoxChecksum_IP.setDisplayIntegerBase(10)
        self.spinBoxChecksum_IP.setObjectName("spinBoxChecksum_IP")
        self.horizontalLayout_29.addWidget(self.spinBoxChecksum_IP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_26 = QtWidgets.QLabel(self.ipv4)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_30.addWidget(self.label_26)
        self.lineSRC_IP = QtWidgets.QLineEdit(self.ipv4)
        self.lineSRC_IP.setClearButtonEnabled(False)
        self.lineSRC_IP.setObjectName("lineSRC_IP")
        self.horizontalLayout_30.addWidget(self.lineSRC_IP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_27 = QtWidgets.QLabel(self.ipv4)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_31.addWidget(self.label_27)
        self.lineDST_IP = QtWidgets.QLineEdit(self.ipv4)
        self.lineDST_IP.setClearButtonEnabled(False)
        self.lineDST_IP.setObjectName("lineDST_IP")
        self.horizontalLayout_31.addWidget(self.lineDST_IP)
        self.verticalLayout_8.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_32 = QtWidgets.QLabel(self.ipv4)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_36.addWidget(self.label_32)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkBox_OptionCopied = QtWidgets.QCheckBox(self.ipv4)
        self.checkBox_OptionCopied.setObjectName("checkBox_OptionCopied")
        self.verticalLayout_7.addWidget(self.checkBox_OptionCopied)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_28 = QtWidgets.QLabel(self.ipv4)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_32.addWidget(self.label_28)
        self.spinBoxI_OptionClass = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxI_OptionClass.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxI_OptionClass.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxI_OptionClass.setWhatsThis("")
        self.spinBoxI_OptionClass.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxI_OptionClass.setSuffix("")
        self.spinBoxI_OptionClass.setMinimum(0)
        self.spinBoxI_OptionClass.setMaximum(3)
        self.spinBoxI_OptionClass.setProperty("value", 0)
        self.spinBoxI_OptionClass.setDisplayIntegerBase(10)
        self.spinBoxI_OptionClass.setObjectName("spinBoxI_OptionClass")
        self.horizontalLayout_32.addWidget(self.spinBoxI_OptionClass)
        self.verticalLayout_7.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_29 = QtWidgets.QLabel(self.ipv4)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_33.addWidget(self.label_29)
        self.spinBoxI_OptionNumber = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxI_OptionNumber.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxI_OptionNumber.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxI_OptionNumber.setWhatsThis("")
        self.spinBoxI_OptionNumber.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxI_OptionNumber.setSuffix("")
        self.spinBoxI_OptionNumber.setMinimum(0)
        self.spinBoxI_OptionNumber.setMaximum(31)
        self.spinBoxI_OptionNumber.setProperty("value", 0)
        self.spinBoxI_OptionNumber.setDisplayIntegerBase(10)
        self.spinBoxI_OptionNumber.setObjectName("spinBoxI_OptionNumber")
        self.horizontalLayout_33.addWidget(self.spinBoxI_OptionNumber)
        self.verticalLayout_7.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_30 = QtWidgets.QLabel(self.ipv4)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_34.addWidget(self.label_30)
        self.spinBoxI_OptionLength = QtWidgets.QSpinBox(self.ipv4)
        self.spinBoxI_OptionLength.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxI_OptionLength.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxI_OptionLength.setWhatsThis("")
        self.spinBoxI_OptionLength.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxI_OptionLength.setSuffix("")
        self.spinBoxI_OptionLength.setMinimum(0)
        self.spinBoxI_OptionLength.setMaximum(255)
        self.spinBoxI_OptionLength.setProperty("value", 0)
        self.spinBoxI_OptionLength.setDisplayIntegerBase(10)
        self.spinBoxI_OptionLength.setObjectName("spinBoxI_OptionLength")
        self.horizontalLayout_34.addWidget(self.spinBoxI_OptionLength)
        self.verticalLayout_7.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_31 = QtWidgets.QLabel(self.ipv4)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_35.addWidget(self.label_31)
        self.plainTextEdit_OptionData = QtWidgets.QPlainTextEdit(self.ipv4)
        self.plainTextEdit_OptionData.setObjectName("plainTextEdit_OptionData")
        self.horizontalLayout_35.addWidget(self.plainTextEdit_OptionData)
        self.verticalLayout_7.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_36)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tab_L3_Widget.addTab(self.ipv4, "")
        self.icmp = QtWidgets.QWidget()
        self.icmp.setObjectName("icmp")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.icmp)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_42 = QtWidgets.QLabel(self.icmp)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_48.addWidget(self.label_42)
        self.spinBoxIType_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxIType_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIType_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIType_ICMP.setWhatsThis("")
        self.spinBoxIType_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIType_ICMP.setSuffix("")
        self.spinBoxIType_ICMP.setMinimum(0)
        self.spinBoxIType_ICMP.setMaximum(255)
        self.spinBoxIType_ICMP.setProperty("value", 0)
        self.spinBoxIType_ICMP.setDisplayIntegerBase(10)
        self.spinBoxIType_ICMP.setObjectName("spinBoxIType_ICMP")
        self.horizontalLayout_48.addWidget(self.spinBoxIType_ICMP)
        self.gridLayout_9.addLayout(self.horizontalLayout_48, 0, 0, 1, 1)
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.label_57 = QtWidgets.QLabel(self.icmp)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_64.addWidget(self.label_57)
        self.spinBoxICode_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxICode_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxICode_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxICode_ICMP.setWhatsThis("")
        self.spinBoxICode_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxICode_ICMP.setSuffix("")
        self.spinBoxICode_ICMP.setMinimum(0)
        self.spinBoxICode_ICMP.setMaximum(255)
        self.spinBoxICode_ICMP.setProperty("value", 0)
        self.spinBoxICode_ICMP.setDisplayIntegerBase(10)
        self.spinBoxICode_ICMP.setObjectName("spinBoxICode_ICMP")
        self.horizontalLayout_64.addWidget(self.spinBoxICode_ICMP)
        self.gridLayout_9.addLayout(self.horizontalLayout_64, 1, 0, 1, 1)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.label_58 = QtWidgets.QLabel(self.icmp)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_65.addWidget(self.label_58)
        self.spinBoxI_ICMPChecksum_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxI_ICMPChecksum_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxI_ICMPChecksum_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxI_ICMPChecksum_ICMP.setWhatsThis("")
        self.spinBoxI_ICMPChecksum_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxI_ICMPChecksum_ICMP.setSuffix("")
        self.spinBoxI_ICMPChecksum_ICMP.setMinimum(0)
        self.spinBoxI_ICMPChecksum_ICMP.setMaximum(65535)
        self.spinBoxI_ICMPChecksum_ICMP.setProperty("value", 0)
        self.spinBoxI_ICMPChecksum_ICMP.setDisplayIntegerBase(10)
        self.spinBoxI_ICMPChecksum_ICMP.setObjectName("spinBoxI_ICMPChecksum_ICMP")
        self.horizontalLayout_65.addWidget(self.spinBoxI_ICMPChecksum_ICMP)
        self.gridLayout_9.addLayout(self.horizontalLayout_65, 2, 0, 1, 1)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.label_59 = QtWidgets.QLabel(self.icmp)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_66.addWidget(self.label_59)
        self.plainTextEdit_ICMPData_ICMP = QtWidgets.QPlainTextEdit(self.icmp)
        self.plainTextEdit_ICMPData_ICMP.setObjectName("plainTextEdit_ICMPData_ICMP")
        self.horizontalLayout_66.addWidget(self.plainTextEdit_ICMPData_ICMP)
        self.gridLayout_9.addLayout(self.horizontalLayout_66, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_37 = QtWidgets.QLabel(self.icmp)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_45.addWidget(self.label_37)
        self.spinBoxIPversion_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxIPversion_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIPversion_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIPversion_ICMP.setWhatsThis("")
        self.spinBoxIPversion_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIPversion_ICMP.setSuffix("")
        self.spinBoxIPversion_ICMP.setMinimum(0)
        self.spinBoxIPversion_ICMP.setMaximum(15)
        self.spinBoxIPversion_ICMP.setProperty("value", 4)
        self.spinBoxIPversion_ICMP.setDisplayIntegerBase(10)
        self.spinBoxIPversion_ICMP.setObjectName("spinBoxIPversion_ICMP")
        self.horizontalLayout_45.addWidget(self.spinBoxIPversion_ICMP)
        self.verticalLayout_9.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_40 = QtWidgets.QLabel(self.icmp)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_46.addWidget(self.label_40)
        self.spinBoxHeaderLength_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxHeaderLength_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxHeaderLength_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxHeaderLength_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxHeaderLength_ICMP.setSuffix("")
        self.spinBoxHeaderLength_ICMP.setMinimum(0)
        self.spinBoxHeaderLength_ICMP.setMaximum(15)
        self.spinBoxHeaderLength_ICMP.setProperty("value", 5)
        self.spinBoxHeaderLength_ICMP.setDisplayIntegerBase(10)
        self.spinBoxHeaderLength_ICMP.setObjectName("spinBoxHeaderLength_ICMP")
        self.horizontalLayout_46.addWidget(self.spinBoxHeaderLength_ICMP)
        self.verticalLayout_9.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_41 = QtWidgets.QLabel(self.icmp)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_47.addWidget(self.label_41)
        self.spinBoxTypeOfService_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxTypeOfService_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxTypeOfService_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxTypeOfService_ICMP.setWhatsThis("")
        self.spinBoxTypeOfService_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxTypeOfService_ICMP.setSuffix("")
        self.spinBoxTypeOfService_ICMP.setMinimum(0)
        self.spinBoxTypeOfService_ICMP.setMaximum(255)
        self.spinBoxTypeOfService_ICMP.setDisplayIntegerBase(10)
        self.spinBoxTypeOfService_ICMP.setObjectName("spinBoxTypeOfService_ICMP")
        self.horizontalLayout_47.addWidget(self.spinBoxTypeOfService_ICMP)
        self.verticalLayout_9.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_43 = QtWidgets.QLabel(self.icmp)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_49.addWidget(self.label_43)
        self.spinBoxTotalLenght_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxTotalLenght_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxTotalLenght_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxTotalLenght_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxTotalLenght_ICMP.setSuffix("")
        self.spinBoxTotalLenght_ICMP.setMinimum(0)
        self.spinBoxTotalLenght_ICMP.setMaximum(65535)
        self.spinBoxTotalLenght_ICMP.setProperty("value", 20)
        self.spinBoxTotalLenght_ICMP.setDisplayIntegerBase(10)
        self.spinBoxTotalLenght_ICMP.setObjectName("spinBoxTotalLenght_ICMP")
        self.horizontalLayout_49.addWidget(self.spinBoxTotalLenght_ICMP)
        self.verticalLayout_9.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_44 = QtWidgets.QLabel(self.icmp)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_50.addWidget(self.label_44)
        self.spinBoxIdentifier_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxIdentifier_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxIdentifier_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxIdentifier_ICMP.setWhatsThis("")
        self.spinBoxIdentifier_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxIdentifier_ICMP.setSuffix("")
        self.spinBoxIdentifier_ICMP.setMaximum(65535)
        self.spinBoxIdentifier_ICMP.setProperty("value", 0)
        self.spinBoxIdentifier_ICMP.setDisplayIntegerBase(10)
        self.spinBoxIdentifier_ICMP.setObjectName("spinBoxIdentifier_ICMP")
        self.horizontalLayout_50.addWidget(self.spinBoxIdentifier_ICMP)
        self.verticalLayout_9.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_45 = QtWidgets.QLabel(self.icmp)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_51.addWidget(self.label_45)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.checkBox_reserved_ICMP = QtWidgets.QCheckBox(self.icmp)
        self.checkBox_reserved_ICMP.setObjectName("checkBox_reserved_ICMP")
        self.horizontalLayout_52.addWidget(self.checkBox_reserved_ICMP)
        self.checkBox_DF_ICMP = QtWidgets.QCheckBox(self.icmp)
        self.checkBox_DF_ICMP.setObjectName("checkBox_DF_ICMP")
        self.horizontalLayout_52.addWidget(self.checkBox_DF_ICMP)
        self.checkBox_MF_ICMP = QtWidgets.QCheckBox(self.icmp)
        self.checkBox_MF_ICMP.setObjectName("checkBox_MF_ICMP")
        self.horizontalLayout_52.addWidget(self.checkBox_MF_ICMP)
        self.horizontalLayout_51.addLayout(self.horizontalLayout_52)
        self.verticalLayout_9.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_46 = QtWidgets.QLabel(self.icmp)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_53.addWidget(self.label_46)
        self.spinBoxFragOffset_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxFragOffset_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxFragOffset_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxFragOffset_ICMP.setWhatsThis("")
        self.spinBoxFragOffset_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxFragOffset_ICMP.setSuffix("")
        self.spinBoxFragOffset_ICMP.setMaximum(8191)
        self.spinBoxFragOffset_ICMP.setProperty("value", 0)
        self.spinBoxFragOffset_ICMP.setDisplayIntegerBase(10)
        self.spinBoxFragOffset_ICMP.setObjectName("spinBoxFragOffset_ICMP")
        self.horizontalLayout_53.addWidget(self.spinBoxFragOffset_ICMP)
        self.verticalLayout_9.addLayout(self.horizontalLayout_53)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_47 = QtWidgets.QLabel(self.icmp)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_54.addWidget(self.label_47)
        self.spinBoxTTL_ICP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxTTL_ICP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxTTL_ICP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxTTL_ICP.setWhatsThis("")
        self.spinBoxTTL_ICP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxTTL_ICP.setSuffix("")
        self.spinBoxTTL_ICP.setMaximum(255)
        self.spinBoxTTL_ICP.setProperty("value", 64)
        self.spinBoxTTL_ICP.setDisplayIntegerBase(10)
        self.spinBoxTTL_ICP.setObjectName("spinBoxTTL_ICP")
        self.horizontalLayout_54.addWidget(self.spinBoxTTL_ICP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_48 = QtWidgets.QLabel(self.icmp)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_55.addWidget(self.label_48)
        self.spinBoxProtocol_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxProtocol_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxProtocol_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxProtocol_ICMP.setWhatsThis("")
        self.spinBoxProtocol_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxProtocol_ICMP.setSuffix("")
        self.spinBoxProtocol_ICMP.setMaximum(255)
        self.spinBoxProtocol_ICMP.setProperty("value", 1)
        self.spinBoxProtocol_ICMP.setDisplayIntegerBase(10)
        self.spinBoxProtocol_ICMP.setObjectName("spinBoxProtocol_ICMP")
        self.horizontalLayout_55.addWidget(self.spinBoxProtocol_ICMP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_49 = QtWidgets.QLabel(self.icmp)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_56.addWidget(self.label_49)
        self.spinBoxChecksum_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxChecksum_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxChecksum_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxChecksum_ICMP.setWhatsThis("")
        self.spinBoxChecksum_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxChecksum_ICMP.setSuffix("")
        self.spinBoxChecksum_ICMP.setMaximum(65535)
        self.spinBoxChecksum_ICMP.setProperty("value", 0)
        self.spinBoxChecksum_ICMP.setDisplayIntegerBase(10)
        self.spinBoxChecksum_ICMP.setObjectName("spinBoxChecksum_ICMP")
        self.horizontalLayout_56.addWidget(self.spinBoxChecksum_ICMP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_50 = QtWidgets.QLabel(self.icmp)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_57.addWidget(self.label_50)
        self.lineSRC_IP_ICMP = QtWidgets.QLineEdit(self.icmp)
        self.lineSRC_IP_ICMP.setClearButtonEnabled(False)
        self.lineSRC_IP_ICMP.setObjectName("lineSRC_IP_ICMP")
        self.horizontalLayout_57.addWidget(self.lineSRC_IP_ICMP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_51 = QtWidgets.QLabel(self.icmp)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_58.addWidget(self.label_51)
        self.lineDST_IP_ICMP = QtWidgets.QLineEdit(self.icmp)
        self.lineDST_IP_ICMP.setClearButtonEnabled(False)
        self.lineDST_IP_ICMP.setObjectName("lineDST_IP_ICMP")
        self.horizontalLayout_58.addWidget(self.lineDST_IP_ICMP)
        self.verticalLayout_10.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_52 = QtWidgets.QLabel(self.icmp)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_59.addWidget(self.label_52)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.checkBox_OptionCopied_ICMP = QtWidgets.QCheckBox(self.icmp)
        self.checkBox_OptionCopied_ICMP.setObjectName("checkBox_OptionCopied_ICMP")
        self.verticalLayout_11.addWidget(self.checkBox_OptionCopied_ICMP)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_53 = QtWidgets.QLabel(self.icmp)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_60.addWidget(self.label_53)
        self.spinBoxI_OptionClass_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxI_OptionClass_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxI_OptionClass_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxI_OptionClass_ICMP.setWhatsThis("")
        self.spinBoxI_OptionClass_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxI_OptionClass_ICMP.setSuffix("")
        self.spinBoxI_OptionClass_ICMP.setMinimum(0)
        self.spinBoxI_OptionClass_ICMP.setMaximum(3)
        self.spinBoxI_OptionClass_ICMP.setProperty("value", 0)
        self.spinBoxI_OptionClass_ICMP.setDisplayIntegerBase(10)
        self.spinBoxI_OptionClass_ICMP.setObjectName("spinBoxI_OptionClass_ICMP")
        self.horizontalLayout_60.addWidget(self.spinBoxI_OptionClass_ICMP)
        self.verticalLayout_11.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_54 = QtWidgets.QLabel(self.icmp)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_61.addWidget(self.label_54)
        self.spinBoxI_OptionNumber_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxI_OptionNumber_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxI_OptionNumber_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxI_OptionNumber_ICMP.setWhatsThis("")
        self.spinBoxI_OptionNumber_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxI_OptionNumber_ICMP.setSuffix("")
        self.spinBoxI_OptionNumber_ICMP.setMinimum(0)
        self.spinBoxI_OptionNumber_ICMP.setMaximum(31)
        self.spinBoxI_OptionNumber_ICMP.setProperty("value", 0)
        self.spinBoxI_OptionNumber_ICMP.setDisplayIntegerBase(10)
        self.spinBoxI_OptionNumber_ICMP.setObjectName("spinBoxI_OptionNumber_ICMP")
        self.horizontalLayout_61.addWidget(self.spinBoxI_OptionNumber_ICMP)
        self.verticalLayout_11.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_55 = QtWidgets.QLabel(self.icmp)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_62.addWidget(self.label_55)
        self.spinBoxI_OptionLength_ICMP = QtWidgets.QSpinBox(self.icmp)
        self.spinBoxI_OptionLength_ICMP.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxI_OptionLength_ICMP.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBoxI_OptionLength_ICMP.setWhatsThis("")
        self.spinBoxI_OptionLength_ICMP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxI_OptionLength_ICMP.setSuffix("")
        self.spinBoxI_OptionLength_ICMP.setMinimum(0)
        self.spinBoxI_OptionLength_ICMP.setMaximum(255)
        self.spinBoxI_OptionLength_ICMP.setProperty("value", 0)
        self.spinBoxI_OptionLength_ICMP.setDisplayIntegerBase(10)
        self.spinBoxI_OptionLength_ICMP.setObjectName("spinBoxI_OptionLength_ICMP")
        self.horizontalLayout_62.addWidget(self.spinBoxI_OptionLength_ICMP)
        self.verticalLayout_11.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_56 = QtWidgets.QLabel(self.icmp)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_63.addWidget(self.label_56)
        self.plainTextEdit_OptionData_ICMP = QtWidgets.QPlainTextEdit(self.icmp)
        self.plainTextEdit_OptionData_ICMP.setObjectName("plainTextEdit_OptionData_ICMP")
        self.horizontalLayout_63.addWidget(self.plainTextEdit_OptionData_ICMP)
        self.verticalLayout_11.addLayout(self.horizontalLayout_63)
        self.horizontalLayout_59.addLayout(self.verticalLayout_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_59)
        self.gridLayout_10.addLayout(self.verticalLayout_10, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.tab_L3_Widget.addTab(self.icmp, "")
        self.horizontalLayout_3.addWidget(self.tab_L3_Widget)
        self.tab_L2_Widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_L2_Widget.setObjectName("tab_L2_Widget")
        self.mac = QtWidgets.QWidget()
        self.mac.setObjectName("mac")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.mac)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_60 = QtWidgets.QLabel(self.mac)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_5.addWidget(self.label_60)
        self.lineEdit_Preamble = QtWidgets.QLineEdit(self.mac)
        self.lineEdit_Preamble.setMaxLength(56)
        self.lineEdit_Preamble.setCursorPosition(0)
        self.lineEdit_Preamble.setObjectName("lineEdit_Preamble")
        self.horizontalLayout_5.addWidget(self.lineEdit_Preamble)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_61 = QtWidgets.QLabel(self.mac)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_6.addWidget(self.label_61)
        self.lineEdit_SFD = QtWidgets.QLineEdit(self.mac)
        self.lineEdit_SFD.setMaxLength(8)
        self.lineEdit_SFD.setCursorPosition(0)
        self.lineEdit_SFD.setObjectName("lineEdit_SFD")
        self.horizontalLayout_6.addWidget(self.lineEdit_SFD)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_62 = QtWidgets.QLabel(self.mac)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_67.addWidget(self.label_62)
        self.lineSRC_MAC = QtWidgets.QLineEdit(self.mac)
        self.lineSRC_MAC.setClearButtonEnabled(False)
        self.lineSRC_MAC.setObjectName("lineSRC_MAC")
        self.horizontalLayout_67.addWidget(self.lineSRC_MAC)
        self.verticalLayout_3.addLayout(self.horizontalLayout_67)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_63 = QtWidgets.QLabel(self.mac)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_68.addWidget(self.label_63)
        self.lineDST_MAC = QtWidgets.QLineEdit(self.mac)
        self.lineDST_MAC.setClearButtonEnabled(False)
        self.lineDST_MAC.setObjectName("lineDST_MAC")
        self.horizontalLayout_68.addWidget(self.lineDST_MAC)
        self.verticalLayout_3.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_64 = QtWidgets.QLabel(self.mac)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_37.addWidget(self.label_64)
        self.spinBox_Lenght = QtWidgets.QSpinBox(self.mac)
        self.spinBox_Lenght.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBox_Lenght.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.spinBox_Lenght.setWhatsThis("")
        self.spinBox_Lenght.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_Lenght.setSuffix("")
        self.spinBox_Lenght.setMaximum(65535)
        self.spinBox_Lenght.setProperty("value", 0)
        self.spinBox_Lenght.setDisplayIntegerBase(10)
        self.spinBox_Lenght.setObjectName("spinBox_Lenght")
        self.horizontalLayout_37.addWidget(self.spinBox_Lenght)
        self.verticalLayout_3.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_65 = QtWidgets.QLabel(self.mac)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_42.addWidget(self.label_65)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.mac)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_42.addWidget(self.plainTextEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_66 = QtWidgets.QLabel(self.mac)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_69.addWidget(self.label_66)
        self.lineEdit = QtWidgets.QLineEdit(self.mac)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_69.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_69)
        self.gridLayout_11.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tab_L2_Widget.addTab(self.mac, "")
        self.horizontalLayout_3.addWidget(self.tab_L2_Widget)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboInterfacesBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboInterfacesBox.setAccessibleDescription("")
        self.comboInterfacesBox.setObjectName("comboInterfacesBox")
        self.gridLayout_2.addWidget(self.comboInterfacesBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(232, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.delaySpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.delaySpinBox.setEnabled(True)
        self.delaySpinBox.setMaximum(10000)
        self.delaySpinBox.setSingleStep(10)
        self.delaySpinBox.setProperty("value", 10)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.gridLayout.addWidget(self.delaySpinBox, 0, 2, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 0, 4, 1, 1)
        self.timesSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.timesSpinBox.setMaximum(10000)
        self.timesSpinBox.setProperty("value", 1)
        self.timesSpinBox.setObjectName("timesSpinBox")
        self.gridLayout.addWidget(self.timesSpinBox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        PacketSender.setCentralWidget(self.centralwidget)
        self.action1 = QtWidgets.QAction(PacketSender)
        self.action1.setCheckable(True)
        self.action1.setObjectName("action1")

        self.retranslateUi(PacketSender)
        self.tab_L4_Widget.setCurrentIndex(0)
        self.tab_L3_Widget.setCurrentIndex(0)
        self.tab_L2_Widget.setCurrentIndex(0)
        self.tab_L4_Widget.currentChanged['int'].connect(self.spinBoxProtocol.stepUp)
        QtCore.QMetaObject.connectSlotsByName(PacketSender)

    def retranslateUi(self, PacketSender):
        _translate = QtCore.QCoreApplication.translate
        PacketSender.setWindowTitle(_translate("PacketSender", "MainWindow"))
        self.label_5.setText(_translate("PacketSender", "SRC Port"))
        self.spinBoxSrcPort_TCP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_4.setText(_translate("PacketSender", "DST Port"))
        self.spinBoxDstPort_TCP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_6.setText(_translate("PacketSender", "SEQ Number"))
        self.spinBoxSEQ.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_7.setText(_translate("PacketSender", "ACK Number"))
        self.spinBoxACK.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_8.setText(_translate("PacketSender", "Data Offset"))
        self.spinBoxDataOffset.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_9.setText(_translate("PacketSender", "Reserved bits"))
        self.checkBox_Reserved1.setText(_translate("PacketSender", "Res 1"))
        self.checkBox_Reserved2.setText(_translate("PacketSender", "Res 2"))
        self.checkBox_Reserved3.setText(_translate("PacketSender", "Res 3"))
        self.checkBox_Reserved4.setText(_translate("PacketSender", "Res 4"))
        self.checkBox_Reserved5.setText(_translate("PacketSender", "CWR"))
        self.checkBox_Reserved6.setText(_translate("PacketSender", "ECE"))
        self.label_10.setText(_translate("PacketSender", "Control bits"))
        self.checkBox_.setText(_translate("PacketSender", "URG"))
        self.checkBox_ACK.setText(_translate("PacketSender", "ACK"))
        self.checkBox_PSH.setText(_translate("PacketSender", "PSH"))
        self.checkBox_RST.setText(_translate("PacketSender", "RST"))
        self.checkBox_SYN.setText(_translate("PacketSender", "SYN"))
        self.checkBox_FIN.setText(_translate("PacketSender", "FIN"))
        self.label_11.setText(_translate("PacketSender", "Window size"))
        self.spinBoxWIN.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_12.setText(_translate("PacketSender", "Checksum"))
        self.spinBoxChecksum_TCP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_13.setText(_translate("PacketSender", "Urgent pointers"))
        self.spinBoxUrgent.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_14.setText(_translate("PacketSender", "Options"))
        self.checkBox_NOPS.setText(_translate("PacketSender", "Add two NOPs (16bits)"))
        self.checkBox_Timestamp.setText(_translate("PacketSender", "Add Timestamp (80bits)"))
        self.label_38.setText(_translate("PacketSender", "Data"))
        self.plainTextEdit_TCP_Data.setPlaceholderText(_translate("PacketSender", "Only plain text, sorry"))
        self.tab_L4_Widget.setTabText(self.tab_L4_Widget.indexOf(self.tcp), _translate("PacketSender", "TCP"))
        self.label_34.setText(_translate("PacketSender", "SRC Port"))
        self.spinBoxSrcPort_UDP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_33.setText(_translate("PacketSender", "DST Port"))
        self.spinBoxDstPort_UDP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_35.setText(_translate("PacketSender", "Length"))
        self.spinBoxLength_UDP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_36.setText(_translate("PacketSender", "Checksum"))
        self.spinBoxChecksum_UDP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_39.setText(_translate("PacketSender", "Data"))
        self.plainTextEdit_UDP_Data_2.setPlaceholderText(_translate("PacketSender", "Only plain text, sorry"))
        self.tab_L4_Widget.setTabText(self.tab_L4_Widget.indexOf(self.udp), _translate("PacketSender", "UDP"))
        self.label_15.setText(_translate("PacketSender", "Version"))
        self.spinBoxIPversion.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_16.setText(_translate("PacketSender", "IHL"))
        self.spinBoxIHL.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBoxIHL.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 5 in standard</p><p><br/></p><p><br/></p></body></html>"))
        self.label_17.setText(_translate("PacketSender", "DSCP"))
        self.spinBoxIDSCP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_18.setText(_translate("PacketSender", "ECN"))
        self.spinBoxIECN.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_19.setText(_translate("PacketSender", "Total length"))
        self.spinBoxTotalLenght.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBoxTotalLenght.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 20 in standard</p><p><br/></p></body></html>"))
        self.label_21.setText(_translate("PacketSender", "Identification"))
        self.spinBoxIdentification.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_20.setText(_translate("PacketSender", "Flags"))
        self.checkBox_reserved.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Must be 0</p><p><br/></p></body></html>"))
        self.checkBox_reserved.setText(_translate("PacketSender", "Res"))
        self.checkBox_DF.setText(_translate("PacketSender", "DF"))
        self.checkBox_MF.setText(_translate("PacketSender", "MF"))
        self.label_22.setText(_translate("PacketSender", "Fragment offset"))
        self.spinBoxFragOffset.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_23.setText(_translate("PacketSender", "TTL"))
        self.spinBoxTTL.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_24.setText(_translate("PacketSender", "Protocol"))
        self.spinBoxProtocol.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_25.setText(_translate("PacketSender", "Checksum"))
        self.spinBoxChecksum_IP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_26.setText(_translate("PacketSender", "SRC IP"))
        self.lineSRC_IP.setInputMask(_translate("PacketSender", "009.009.009.009;_"))
        self.label_27.setText(_translate("PacketSender", "DST IP"))
        self.lineDST_IP.setInputMask(_translate("PacketSender", "009.009.009.009;_"))
        self.label_32.setText(_translate("PacketSender", "Options"))
        self.checkBox_OptionCopied.setText(_translate("PacketSender", "Copied"))
        self.label_28.setText(_translate("PacketSender", "Class"))
        self.spinBoxI_OptionClass.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_29.setText(_translate("PacketSender", "Number"))
        self.spinBoxI_OptionNumber.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_30.setText(_translate("PacketSender", "Length"))
        self.spinBoxI_OptionLength.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_31.setText(_translate("PacketSender", "Data"))
        self.tab_L3_Widget.setTabText(self.tab_L3_Widget.indexOf(self.ipv4), _translate("PacketSender", "IPv4"))
        self.label_42.setText(_translate("PacketSender", "Type"))
        self.spinBoxIType_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_57.setText(_translate("PacketSender", "Code"))
        self.spinBoxICode_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_58.setText(_translate("PacketSender", "ICMP Checksum"))
        self.spinBoxI_ICMPChecksum_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_59.setText(_translate("PacketSender", "Data"))
        self.plainTextEdit_ICMPData_ICMP.setPlaceholderText(_translate("PacketSender", "Only plain text, sorry"))
        self.label_37.setText(_translate("PacketSender", "Version"))
        self.spinBoxIPversion_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_40.setText(_translate("PacketSender", "Header Length"))
        self.spinBoxHeaderLength_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBoxHeaderLength_ICMP.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 5 in standard</p><p><br/></p><p><br/></p></body></html>"))
        self.label_41.setText(_translate("PacketSender", "Type of Service"))
        self.spinBoxTypeOfService_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_43.setText(_translate("PacketSender", "Total length"))
        self.spinBoxTotalLenght_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.spinBoxTotalLenght_ICMP.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Minimum 20 in standard</p><p><br/></p></body></html>"))
        self.label_44.setText(_translate("PacketSender", "Identifier"))
        self.spinBoxIdentifier_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_45.setText(_translate("PacketSender", "Flags"))
        self.checkBox_reserved_ICMP.setWhatsThis(_translate("PacketSender", "<html><head/><body><p>Must be 0</p><p><br/></p></body></html>"))
        self.checkBox_reserved_ICMP.setText(_translate("PacketSender", "Res"))
        self.checkBox_DF_ICMP.setText(_translate("PacketSender", "DF"))
        self.checkBox_MF_ICMP.setText(_translate("PacketSender", "MF"))
        self.label_46.setText(_translate("PacketSender", "Fragment offset"))
        self.spinBoxFragOffset_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_47.setText(_translate("PacketSender", "TTL"))
        self.spinBoxTTL_ICP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_48.setText(_translate("PacketSender", "Protocol"))
        self.spinBoxProtocol_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_49.setText(_translate("PacketSender", "Checksum"))
        self.spinBoxChecksum_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_50.setText(_translate("PacketSender", "SRC IP"))
        self.lineSRC_IP_ICMP.setInputMask(_translate("PacketSender", "009.009.009.009;_"))
        self.label_51.setText(_translate("PacketSender", "DST IP"))
        self.lineDST_IP_ICMP.setInputMask(_translate("PacketSender", "009.009.009.009;_"))
        self.label_52.setText(_translate("PacketSender", "Options"))
        self.checkBox_OptionCopied_ICMP.setText(_translate("PacketSender", "Copied"))
        self.label_53.setText(_translate("PacketSender", "Class"))
        self.spinBoxI_OptionClass_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_54.setText(_translate("PacketSender", "Number"))
        self.spinBoxI_OptionNumber_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_55.setText(_translate("PacketSender", "Length"))
        self.spinBoxI_OptionLength_ICMP.setToolTip(_translate("PacketSender", "<html><head/><body><p>SRC port</p></body></html>"))
        self.label_56.setText(_translate("PacketSender", "Data"))
        self.plainTextEdit_OptionData_ICMP.setPlaceholderText(_translate("PacketSender", "Only plain text, sorry"))
        self.tab_L3_Widget.setTabText(self.tab_L3_Widget.indexOf(self.icmp), _translate("PacketSender", "ICMP"))
        self.label_60.setText(_translate("PacketSender", "Preamble"))
        self.lineEdit_Preamble.setText(_translate("PacketSender", "10101010101010101010101010101010101010101010101010101010"))
        self.label_61.setText(_translate("PacketSender", "SFD"))
        self.lineEdit_SFD.setText(_translate("PacketSender", "10101011"))
        self.label_62.setText(_translate("PacketSender", "SRC MAC"))
        self.lineSRC_MAC.setInputMask(_translate("PacketSender", "HH:HH:HH:HH:HH:HH;_"))
        self.label_63.setText(_translate("PacketSender", "DST MAC"))
        self.lineDST_MAC.setInputMask(_translate("PacketSender", "HH:HH:HH:HH:HH:HH;_"))
        self.label_64.setText(_translate("PacketSender", "Lenght"))
        self.spinBox_Lenght.setToolTip(_translate("PacketSender", "<html><head/><body><p>DST port</p></body></html>"))
        self.label_65.setText(_translate("PacketSender", "Data"))
        self.label_66.setText(_translate("PacketSender", "CRC"))
        self.tab_L2_Widget.setTabText(self.tab_L2_Widget.indexOf(self.mac), _translate("PacketSender", "MAC"))
        self.label_3.setText(_translate("PacketSender", "Interface:"))
        self.label_2.setText(_translate("PacketSender", "ms"))
        self.sendButton.setText(_translate("PacketSender", "Send"))
        self.label.setText(_translate("PacketSender", "times every "))
        self.action1.setText(_translate("PacketSender", "1"))
        self.action1.setToolTip(_translate("PacketSender", "2"))
